# IMPORT DATA

In [1]:
#library untuk membuat, mengubah dan mengecek data pada tabel
import pandas as pd
pd.set_option('display.max_colwidth', 200)
import numpy as np
#Membaca data csv
data_path = "C:\\Users\\HP\\Downloads\\TUGAS AKHIR\EXCEL KODINGAN\\DataProdukVers6.csv"
data_product = pd.read_csv(data_path)

#Menampilkan data
data_product.head(1)

,No,Nama,Name,Jenis,Merk,Jenis Kulit,Permasalahan Kulit,Deskripsi,Kandungan,Gambar
0,1,Marigold Deep-Cleanse Facial Wash,Marigold Deep-Cleanse,Facial Wash,NPure,"normal, berminyak, kering, kombinasi","normal, kusam","Pembersih muka dengan busa lembut yang memiliki kandungan Ekstrak Marigold dan 8X Essential Vitamins yang dapat membersihkan kulit dari polusi debu dan kotoran. Diperkaya dengan 5X Peptides, Adeno...","Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glycinate, Calendula Officinalis Flower Extract, Butylene Glycol, Palmitoyl Tripeptide-5, Palmitoyl Te...",https://www.beautyhaul.com/assets/uploads/products/thumbs/800x800/NPURE_Marigold_Deep-Cleanse_Facial_Wash_100gr.webp

# TEXT PREPROCESSING

In [2]:
#Drop kolom yang tidak dibutuhkan
data_product = data_product.drop(labels=["No","Merk","Deskripsi","Gambar"], axis='columns')

data_product.head(5)

,Nama,Name,Jenis,Jenis Kulit,Permasalahan Kulit,Kandungan
0,Marigold Deep-Cleanse Facial Wash,Marigold Deep-Cleanse,Facial Wash,"normal, berminyak, kering, kombinasi","normal, kusam","Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glycinate, Calendula Officinalis Flower Extract, Butylene Glycol, Palmitoyl Tripeptide-5, Palmitoyl Te..."
1,Acne Facial Wash,Acne,Facial Wash,"normal, berminyak, kombinasi","normal, kusam","Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg-40 Hydrogenated Castor Oil, Cocamidopropyl Betaine, Phenoxyethanol, Aminomethyl Propanol, Sodium Chloride, Citrus Limon (..."
2,Hy! Amino Wow-tery Hydrating Facial Wash,Hy! Amino Wow-tery Hydrating,Facial Wash,"normal, kering","normal, kusam","Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, Decyl Glucoside, Phenoxyethanol, Potassium Laureth Phosphate, PEG-7..."
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Hy! Amino Ac-TtackAnti-Acne,Facial Wash,"normal, berminyak, kering","normal, jerawat, kusam","Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, Decyl Glucoside, Phenoxyethanol, Sodium Benzoate, Potassium Laureth..."
4,Hy! Amino Control Oil Control Facial Wash,Hy! Amino Control Oil Control,Facial Wash,kering,kusam,"Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, Decyl Glucoside, Potassium Laureth Phosphate, Distearyl Phthalic Ac..."

In [3]:
data_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Nama                100 non-null    object
 1   Name                100 non-null    object
 2   Jenis               100 non-null    object
 3   Jenis Kulit         100 non-null    object
 4   Permasalahan Kulit  100 non-null    object
 5   Kandungan           100 non-null    object
dtypes: object(6)
memory usage: 4.8+ KB

In [4]:
data_textPre = pd.DataFrame()
data_textPre['data awal'] = data_product['Nama'] + " " + data_product['Jenis '] + " " + data_product['Jenis Kulit'] + " " + data_product['Permasalahan Kulit'] + " " + data_product['Kandungan']

In [5]:
data_textPre[['data awal']].head(5)

                                                                                                                                                                                                 data awal
0  Marigold Deep-Cleanse Facial Wash Facial Wash normal, berminyak, kering, kombinasi normal, kusam Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glyci...
1  Acne Facial Wash Facial Wash normal, berminyak, kombinasi normal, kusam Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg-40 Hydrogenated Castor Oil, Cocamidopropyl Betain...
2  Hy! Amino Wow-tery Hydrating Facial Wash Facial Wash normal, kering normal, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glyc...
3  Hy! Amino Ac-TtackAnti-Acne Facial Wash Facial Wash normal, berminyak, kering normal, jerawat, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, So...
4  Hy! Amino Control Oil Control Facial Wash Facial Wash kering kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, ...



## CASE FOLDING

In [6]:
data_caseFolding = pd.DataFrame(data=data_textPre['data awal'])
data_caseFolding.rename(columns={'data awal': 'case folding'}, inplace=True)
# Case Folding
for i in range(0, len(data_caseFolding)):
  data_caseFolding['case folding'][i] = data_caseFolding['case folding'][i].lower()

In [7]:
data_caseFolding.head(3)

                                                                                                                                                                                              case folding
0  marigold deep-cleanse facial wash facial wash normal, berminyak, kering, kombinasi normal, kusam water, glycerin, coco-betaine, disodium cocoamphodiacetate, sodium chloride, potassium cocoyl glyci...
1  acne facial wash facial wash normal, berminyak, kombinasi normal, kusam aqua, lauryl glucoside, acrylates copolymer, sodium cocoyl glyrcinate, peg-40 hydrogenated castor oil, cocamidopropyl betain...
2  hy! amino wow-tery hydrating facial wash facial wash normal, kering normal, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glyc...

## TOKENIZING

In [8]:
pip install nltk

Requirement already satisfied: nltk in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from nltk) (2023.3.23)
Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python38\site-packages (from click->nltk) (0.4.4)
Note: you may need to restart the kernel to use updated packages.

In [9]:
#Mengimport nltk
import nltk
#Mendownload package untuk menghapus tanda baca
nltk.download('punkt')

#import reguler expression
import re
#import string
import string

# impor word_tokenize dari modul nltk
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [10]:
# Tokenizing
data_tokenizing = pd.DataFrame(data=data_caseFolding['case folding'])
data_tokenizing.rename(columns={'case folding': 'tokenizing'}, inplace=True)

for i in range(0, len(data_tokenizing)):
  # Menghapus Angka
  data_tokenizing['tokenizing'][i] = re.sub(
      r"\d+", "", data_tokenizing['tokenizing'][i])
  # Menghapus Tanda Baca
  data_tokenizing['tokenizing'][i] = data_tokenizing['tokenizing'][i].translate(
      str.maketrans('', '', string.punctuation))
  # Menghapus Simbol (@)
  data_tokenizing['tokenizing'][i] = re.sub(
      r"@\S+", "", data_tokenizing['tokenizing'][i])
  # Menghapus URL
  data_tokenizing['tokenizing'][i] = re.sub(
      "http[s]?\://\S+", "", data_tokenizing['tokenizing'][i])
  # Menghapus tab atau line karakter
  data_tokenizing['tokenizing'][i] = re.sub(
      r"\n", "", data_tokenizing['tokenizing'][i])
  # Menghapus single alpabet
  data_tokenizing['tokenizing'][i] = re.sub(
      r"\b[a-zA-Z]\b", "", data_tokenizing['tokenizing'][i])
  # Menghapus berlebihan spasi
  data_tokenizing['tokenizing'][i] = re.sub(
      '\s+', ' ', data_tokenizing['tokenizing'][i])
  # Memisahkan kata menggunakan word_tokenize
  data_tokenizing['tokenizing'][i] = nltk.word_tokenize(
      data_tokenizing['tokenizing'][i])

In [11]:
data_tokenizing.head(3)

                                                                                                                                                                                                tokenizing
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, cocoamphodiacetate, sodium, chloride, potassium, co...
1  [acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidop...
2  [hy, amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium,...

## FILTERING

In [12]:
# Filtering
from nltk.corpus import stopwords
data_filtering = pd.DataFrame(data=data_tokenizing['tokenizing'])
data_filtering.rename(columns={'tokenizing': 'filtering'}, inplace=True)

# Mendownload package stopwords untuk menghapus kata kata yang tidak berarti dalam sebuah kalimat
nltk.download('stopwords')

# Stopword Bahasa Indonesia
indo_stopword = (stopwords.words('indonesian'))

# Stopword Bahasa Inggris
eng_stopword = (stopwords.words('english'))

# Data Stopword
data_stopword = indo_stopword
data_stopword.extend(eng_stopword)
data_stopword = str(data_stopword)
# display(data_stopword)

for i in range(0, len(data_filtering)):
  data_filtering['filtering'][i] = [
      word for word in data_filtering['filtering'][i] if not word in (data_stopword)]

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [13]:
data_filtering.head(3)

                                                                                                                                                                                                 filtering
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, cocoamphodiacetate, sodium, chloride, potassium, co...
1  [acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidop...
2  [amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chl...

## STEMMING

In [14]:
pip install PySastrawi

Requirement already satisfied: PySastrawi in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (1.2.0)Note: you may need to restart the kernel to use updated packages.

In [15]:
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory
data_stemming = pd.DataFrame(data=data_filtering['filtering'])
data_stemming.rename(columns={'filtering': 'stemming'}, inplace=True)
# Stemming

# Membuat stemmer
Factory = StemmerFactory()
Stemmer = Factory.create_stemmer()

for i in range(0, len(data_stemming)):
  temp = []
  for j in range(0, len(data_stemming['stemming'][i])):
    azx = ''
    azx = Stemmer.stem(
        data_stemming['stemming'][i][j])
    temp.append(azx)
  data_stemming['stemming'][i] = temp

In [16]:
data_stemming.head(3)

                                                                                                                                                                                                  stemming
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, minyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, sodium, cocoamphodiacetate, sodium, chloride, potassium, cocoyl,...
1  [acne, facial, wash, facial, wash, normal, minyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidoprop...
2  [amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chl...

In [17]:
data_textPre_res = pd.concat(
    [data_textPre, data_caseFolding, data_tokenizing, data_filtering, data_stemming], axis=1)

# Menggabungkan Kata

In [18]:
# Menggabungkan setiap kata dalam satu data
dataset_res = []

for i in range(0, len(data_textPre_res['stemming'])):
  temp = []
  temp = " ".join(data_textPre_res['stemming'][i])
  dataset_res.append(temp)

dataset = pd.DataFrame(dataset_res, columns=["data"])
dataset.head(3)

                                                                                                                                                                                                      data
0  marigold deepcleanse facial wash facial wash normal minyak kering kombinasi normal kusam water glycerin cocobetaine sodium cocoamphodiacetate sodium chloride potassium cocoyl glycinate calendula o...
1  acne facial wash facial wash normal minyak kombinasi normal kusam aqua lauryl glucoside acrylates copolymer sodium cocoyl glyrcinate peg hydrogenated castor oil cocamidopropyl betaine phenoxyethan...
2  amino wowtery hydrating facial wash facial wash normal kering normal kusam water sodium laureth sulfate cocamidopropyl betaine sodium lauryl sulfate sekken sojik sodium chloride glycol distearate ...

# TF-IDF DAN COSINE SIMILARITY

In [19]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (1.24.2)
Requirement already satisfied: scipy>=1.3.2 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (3.1.0)
Note: you may need to restart the kernel to use updated packages.

## Proses tahapan preprocessing terhadap inputan pengguna

In [20]:
# TEXT PREPROCESSING INPUTAN
def text_pre_input_two(user_input):
  # CASE FOLDING
    user_input = user_input.lower()

  # TOKENIZING
    # Menghapus Angka
    user_input = re.sub(r"\d+", "", user_input)
    # Menghapus Tanda Baca
    user_input = user_input.translate(
        str.maketrans("", "", string.punctuation))
    # Menghapus Simbol (@)
    user_input = re.sub(r"@\S+", "", user_input)
    # Menghapus URL
    user_input = re.sub("http[s]?\://\S+", "", user_input)
    # Menghapus tab atau line karakter
    user_input = re.sub(r"\n", "", user_input)
    # Menghapus berlebihan spasi
    user_input = re.sub('\s+', ' ', user_input)
    # dilakukan proses tokenization pada user_input
    tokens_query = [str(tok) for tok in nltk.word_tokenize(user_input)]

  # FILTERING
    # Stopword Bahasa Indonesia
    indo_stopword = set(stopwords.words('indonesian'))

    # Stopword Bahasa Inggris
    eng_stopword = set(stopwords.words('english'))

    # Data Stopword
    data_stopword = str(indo_stopword) + " " + str(eng_stopword)

    # Data tanpa stopword
    tokens_query = [word for word in tokens_query if not word in data_stopword]

  # STEMMING
    the_query = []
    # Membuat stemmer
    Factory = StemmerFactory()
    Stemmer = Factory.create_stemmer()
    for i in range(0, len(tokens_query)):
        tokens_query[i] = Stemmer.stem(tokens_query[i])
        the_query.append(tokens_query[i])

    join_query = ' '.join(tokens_query)
    return (join_query)

## Proses perhitungan cosine similarity untuk mendapatkan rekomendasi produk

In [21]:
# COSINE SIMILARITY AND GET THE RECOMMENDATION
from sklearn.metrics.pairwise import cosine_similarity


def get_recommendations_product_two(tfidf_dataset):

    # Mencari tingkat kemiripan antara user_input dengan dataset
    cos_sim = cosine_similarity(tfidf_dataset, tfidf_dataset)
    # print(cos_sim)
    df_cosim = pd.DataFrame(data=cos_sim)
    # display(df_cosim)

    # Mengambil nilai cosine similarity pada baris yang berisi inputan pengguna
    val_cos_sim = pd.DataFrame(
        data=cos_sim[-1, :], columns=['Cosine Similarity Score'])
    # display(val_cos_sim)

    # Mencari 5 teratas nilai kemiripan tertinggi
    top5 = val_cos_sim.sort_values(
        "Cosine Similarity Score", ascending=False)[1:6]
    # display(top5)

    # Mencari index dari 5 nilai kemiripan teratas
    index = list(top5.index.values)

    return index, top5

# 5 RECOMMENDATION

## IMPORT DATA PENGGUNA

In [22]:
data_path = "C:\\Users\\HP\\Downloads\\TUGAS AKHIR\EXCEL KODINGAN\\DataDokter.csv"
data_pengguna = pd.read_csv(data_path)
data_pengguna.head(5)

,No,Jenis Produk,Jenis Kulit,Permasalahan Kulit,Kandungan
0,11,Facial Wash,Kombinasi,Kusam,"Glycerin, Retinol, Alpha Hydroxy Acids (AHA), Niacinamide, Licorice Root Extract"
1,12,Facial Wash,Kombinasi,Jerawat,"Glycerin, Salicylic Acid, Niacinamide, Azelaic Acid, Benzoyl Peroxide"
2,13,Face Toner,Normal,Normal,"Sodium Hyaluronate, Glycerin, Rosemary, Centella Asiatica, Tranexamic"
3,14,Face Toner,Normal,Kusam,"Niacinamide, Licorice Root Extract, Alpha Hydroxy Acids (AHA), Vitamin C, Retinol"
4,15,Face Toner,Normal,Jerawat,"Salicylic Acid, Azelaic Acid, Tea Tree Oil, Benzoyl Peroxide, Dimethicone"

In [23]:
data_pengguna = data_pengguna.drop(labels=["No"], axis='columns')

In [24]:
data_pengguna["Kandungan"].fillna(" ", inplace=True)

## MEMBUAT DATA KEMUNGKINAN INPUTAN PENGGUNA

In [25]:
data_pengguna['input'] = data_pengguna['Jenis Produk'] + " " +  data_pengguna['Jenis Kulit'] + " " + data_pengguna['Permasalahan Kulit'] + " " + data_pengguna['Kandungan']

data_pengguna.head(5)

,Jenis Produk,Jenis Kulit,Permasalahan Kulit,Kandungan,input
0,Facial Wash,Kombinasi,Kusam,"Glycerin, Retinol, Alpha Hydroxy Acids (AHA), Niacinamide, Licorice Root Extract","Facial Wash Kombinasi Kusam Glycerin, Retinol, Alpha Hydroxy Acids (AHA), Niacinamide, Licorice Root Extract"
1,Facial Wash,Kombinasi,Jerawat,"Glycerin, Salicylic Acid, Niacinamide, Azelaic Acid, Benzoyl Peroxide","Facial Wash Kombinasi Jerawat Glycerin, Salicylic Acid, Niacinamide, Azelaic Acid, Benzoyl Peroxide"
2,Face Toner,Normal,Normal,"Sodium Hyaluronate, Glycerin, Rosemary, Centella Asiatica, Tranexamic","Face Toner Normal Normal Sodium Hyaluronate, Glycerin, Rosemary, Centella Asiatica, Tranexamic"
3,Face Toner,Normal,Kusam,"Niacinamide, Licorice Root Extract, Alpha Hydroxy Acids (AHA), Vitamin C, Retinol","Face Toner Normal Kusam Niacinamide, Licorice Root Extract, Alpha Hydroxy Acids (AHA), Vitamin C, Retinol"
4,Face Toner,Normal,Jerawat,"Salicylic Acid, Azelaic Acid, Tea Tree Oil, Benzoyl Peroxide, Dimethicone","Face Toner Normal Jerawat Salicylic Acid, Azelaic Acid, Tea Tree Oil, Benzoyl Peroxide, Dimethicone"

In [26]:
data_pengguna['input'][0]

'Facial Wash Kombinasi Kusam Glycerin, Retinol, Alpha Hydroxy Acids (AHA), Niacinamide, Licorice Root Extract'

# KODE 2

In [28]:
# TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer

# import modul xlsxwriter untuk membantu menulis data ke excel
import xlsxwriter

# Membuat excel yang menjadi tujuan tuli
writer = pd.ExcelWriter(
    'C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/HasilRekomendasiDokter.xlsx', engine='xlsxwriter')
# writer_two = pd.ExcelWriter(
#     'C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/HasilTFIDF_FIX.xlsx', engine='xlsxwriter')
# Awal penulisan
row = 1
# row_two = 1
col = 0
# col_two = 0

for i in range (0,len(data_pengguna)):
  print(data_pengguna['input'][i]) 

  test_case = data_pengguna['input'][i]

  # TFIDF
  vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))

  # melakuka text preprocessing pada inputan pengguna
  user_input = text_pre_input_two(test_case)
  # menambahkan ke dalam dataset
  add_data = pd.DataFrame({'data': user_input}, index=[-1])
  # print(add_data)

  the_data = data_product
  
  # percabangan agar produk yang direkomendasikan sesuai dengan kategori
  if (test_case.find('Facial Wash') != -1):
    print('Facial Wash')
    th_idx = pd.concat([dataset[0:20], add_data]).reset_index(drop=True)
    the_product = the_data[0:20]
  elif (test_case.find('Face Toner') != -1):
    print('Face Toner')
    th_idx = pd.concat([dataset[20:40], add_data]).reset_index(drop=True)
    the_product = the_data[20:40]
  elif (test_case.find('Face Serum') != -1):
    print('Face Serum')
    th_idx = pd.concat([dataset[40:60], add_data]).reset_index(drop=True)
    the_product = the_data[40:60]
  elif (test_case.find('Moisturizer') != -1):
    print('Moisturizer')
    th_idx = pd.concat([dataset[60:80], add_data]).reset_index(drop=True)
    the_product = the_data[60:80]
  else:
    print('Sunscreen')
    th_idx = pd.concat([dataset[80:100], add_data]).reset_index(drop=True)
    the_product = the_data[80:100]
    
  # Mencari nilai TFIDF dari dataset yang telah ditentukan
  tfidf_dataset1 = vectorizer.fit_transform(th_idx['data'])
  # Mencari rekomendasi berdasarkan nilai cosine similarity yang didapatkan dari nilai TFIDF sebelumnya
  index, top5 = get_recommendations_product_two(tfidf_dataset1)

  res_data = pd.DataFrame(the_product[['Nama', 'Jenis ']].iloc[index])
  top5.index = res_data.index
  fix_res = pd.concat([res_data, top5], axis=1)
  display(fix_res)
  # Hasil rekomendasi dituliskan ke dalam excel
  fix_res.to_excel(writer, startrow=row)

  # Mengakses file excel dan sheet untuk menuliskan sesuatu
  work_book = writer.book
  work_sheet = writer.sheets["Sheet1"]
  row -= 1

  # Menuliskan 'test_case' pada baris dan kolom yang telah ditentukan
  work_sheet.write(row, col, test_case)
  row += 10

# Menyimpan hasil yang telah dituliskan
writer.close()

Facial Wash Kombinasi Kusam Glycerin, Retinol, Alpha Hydroxy Acids (AHA), Niacinamide, Licorice Root Extract
Facial Wash

,Nama,Jenis,Cosine Similarity Score
12,Licorice Bring The Light Cleanser,Facial Wash,0.188721
16,Glowing Brigth Mild Cleanser Foam,Facial Wash,0.084724
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.077542
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.075918
19,Oil Control Mild Cleanser Foam,Facial Wash,0.070610

Facial Wash Kombinasi Jerawat Glycerin, Salicylic Acid, Niacinamide, Azelaic Acid, Benzoyl Peroxide
Facial Wash

,Nama,Jenis,Cosine Similarity Score
18,Acne Buster Mild Cleanser Foam,Facial Wash,0.150589
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.146853
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.140183
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.137439
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.130708

Face Toner Normal Normal Sodium Hyaluronate, Glycerin, Rosemary, Centella Asiatica, Tranexamic
Face Toner

                                   Nama      Jenis   Cosine Similarity Score
21        Moisture Rich Hydrating Toner  Face Toner                 0.316608
22                 Mild Purifying Toner  Face Toner                 0.274185
34      Berry Bounce Facial Toner 150ml  Face Toner                 0.239509
35  Stay Toned. Balancing Essence Toner  Face Toner                 0.235841
23            Multi Acids Glowing Toner  Face Toner                 0.210580

Face Toner Normal Kusam Niacinamide, Licorice Root Extract, Alpha Hydroxy Acids (AHA), Vitamin C, Retinol
Face Toner

,Nama,Jenis,Cosine Similarity Score
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.211177
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.205066
34,Berry Bounce Facial Toner 150ml,Face Toner,0.190694
35,Stay Toned. Balancing Essence Toner,Face Toner,0.187735
25,Miraculous Retinol Toner,Face Toner,0.171260

Face Toner Normal Jerawat Salicylic Acid, Azelaic Acid, Tea Tree Oil, Benzoyl Peroxide, Dimethicone
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.356159
39,Cica Series Face Toner 30ml,Face Toner,0.133111
23,Multi Acids Glowing Toner,Face Toner,0.126365
22,Mild Purifying Toner,Face Toner,0.125302
25,Miraculous Retinol Toner,Face Toner,0.105738

Face Toner Berminyak Normal Niacinamide, Salicylic Acid, Tea Tree Oil, Retinol, Propylene Glycol
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.450054
25,Miraculous Retinol Toner,Face Toner,0.270649
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.206048
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.194652
39,Cica Series Face Toner 30ml,Face Toner,0.177337

Face Toner Berminyak Kusam Niacinamide, Alpha Hydroxy Acids (AHA), Licorice Root Extract, Salicylic Acid, Vitamin C
Face Toner

,Nama,Jenis,Cosine Similarity Score
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.226046
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.208991
23,Multi Acids Glowing Toner,Face Toner,0.201813
39,Cica Series Face Toner 30ml,Face Toner,0.194972
34,Berry Bounce Facial Toner 150ml,Face Toner,0.194129

Face Toner Berminyak Jerawat Azelaic Acid, Salicylic Acid, Niacinamide, Benzoyl Peroxide, Retinol
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.242397
25,Miraculous Retinol Toner,Face Toner,0.159162
39,Cica Series Face Toner 30ml,Face Toner,0.139841
22,Mild Purifying Toner,Face Toner,0.136482
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.134501

Face Toner Kering Normal Glycerin, Hyaluronic Acid, Ceramide, Shea Butter, Squalane
Face Toner

,Nama,Jenis,Cosine Similarity Score
32,Skin Ready Hydrating Booster,Face Toner,0.152302
23,Multi Acids Glowing Toner,Face Toner,0.128697
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.126661
22,Mild Purifying Toner,Face Toner,0.105978
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.096551

Face Toner Kering Kusam Alpha Hydroxy Acid (AHA), Retinol, Niacinamide, Hyaluronic Acid, Ceramide
Face Toner

,Nama,Jenis,Cosine Similarity Score
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.265580
32,Skin Ready Hydrating Booster,Face Toner,0.172217
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.169560
25,Miraculous Retinol Toner,Face Toner,0.163358
23,Multi Acids Glowing Toner,Face Toner,0.157561

Face Toner Kering Jerawat Glycerin, Salicylic Acid, Benzoyl Peroxide, Ceramide, Azelaic Acid
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.260944
22,Mild Purifying Toner,Face Toner,0.154377
23,Multi Acids Glowing Toner,Face Toner,0.144464
39,Cica Series Face Toner 30ml,Face Toner,0.133717
32,Skin Ready Hydrating Booster,Face Toner,0.118789

Face Toner Kombinasi Normal Niacinamide, Vitamin C, Hyaluronic Acid, Glycerin, Salicylic Acid
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.328148
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.294243
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.225805
23,Multi Acids Glowing Toner,Face Toner,0.218259
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.196291

Face Toner Kombinasi Kusam Alpha Hydroxy Acid (AHA), Retinol, Niacinamide, Glycerin, Hyaluronic Acid
Face Toner

,Nama,Jenis,Cosine Similarity Score
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.281790
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.190296
23,Multi Acids Glowing Toner,Face Toner,0.182843
25,Miraculous Retinol Toner,Face Toner,0.173252
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.159912

Face Toner Kombinasi Jerawat Glycerin, Azelaic Acid, Salicylic Acid, Niacinamide, Hyaluronic Acid
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.326763
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.240351
23,Multi Acids Glowing Toner,Face Toner,0.216599
22,Mild Purifying Toner,Face Toner,0.212558
39,Cica Series Face Toner 30ml,Face Toner,0.197252

Face Serum Normal Normal Niacinamide, Glycerin, Licorice Root Extract, Centella Asiatica, Madecassoside
Face Serum

,Nama,Jenis,Cosine Similarity Score
56,Centella Herb Serum,Face Serum,0.235940
53,Pore Tightening & Oil Control Moist Serum,Face Serum,0.215522
40,Licorice Potion Of Light Serum,Face Serum,0.206306
46,Acne Spot Serum,Face Serum,0.204555
41,Cica Biome Acne Serum Essence,Face Serum,0.197539

Face Serum Normal Kusam Retinol, Alpha Hydroxy Acid (AHA), Niacinamide, Licorice Root Extract, Vitamin C
Face Serum

                                    Nama      Jenis   Cosine Similarity Score
52          Retinol Smooth Glowing Serum  Face Serum                 0.257393
40        Licorice Potion Of Light Serum  Face Serum                 0.167640
59  Niacinamide - Brightening Serum 20ml  Face Serum                 0.143354
47             AHA-BHA-PHA Peeling Serum  Face Serum                 0.130849
55              Niacinamide Skin Booster  Face Serum                 0.127603

Face Serum Normal Jerawat Azelaic Acid, Salicylic Acid, Niacinamide, Tea Tree Oil, Madecassoside
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
56                Centella Herb Serum  Face Serum                 0.298869
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.252149
54  Daily Defender Multivitamin Serum  Face Serum                 0.169380
57   AcnePlus Complete Solution Serum  Face Serum                 0.168521
50                  Miracle Oil Serum  Face Serum                 0.166887

Face Serum Berminyak Normal Niacinamide, Retinol, Hyaluronic Acid, Glycerin, Aloe Vera
Face Serum

                                    Nama      Jenis   Cosine Similarity Score
52          Retinol Smooth Glowing Serum  Face Serum                 0.296898
47             AHA-BHA-PHA Peeling Serum  Face Serum                 0.195875
42                       Acne Care Serum  Face Serum                 0.179626
55              Niacinamide Skin Booster  Face Serum                 0.174162
59  Niacinamide - Brightening Serum 20ml  Face Serum                 0.170659

Face Serum Berminyak Kusam Retinol, Alpha Hydroxy Acid (AHA), Niacinamide, Licorice Root Extract, Centella Asiatica
Face Serum

,Nama,Jenis,Cosine Similarity Score
52,Retinol Smooth Glowing Serum,Face Serum,0.254569
56,Centella Herb Serum,Face Serum,0.190803
46,Acne Spot Serum,Face Serum,0.177329
40,Licorice Potion Of Light Serum,Face Serum,0.167012
53,Pore Tightening & Oil Control Moist Serum,Face Serum,0.142972

Face Serum Berminyak Jerawat Niacinamide, Salicylic Acid, Azelaic Acid, Benzoyl Peroxide, Tea Tree Oil
Face Serum

                                    Nama      Jenis   Cosine Similarity Score
56                   Centella Herb Serum  Face Serum                 0.272291
47             AHA-BHA-PHA Peeling Serum  Face Serum                 0.223079
57      AcnePlus Complete Solution Serum  Face Serum                 0.148629
54     Daily Defender Multivitamin Serum  Face Serum                 0.147764
59  Niacinamide - Brightening Serum 20ml  Face Serum                 0.142308

Face Serum Kering Normal Ceramide, Glycerin, Hyaluronic Acid, Squalene, Shea Butter
Face Serum

                              Nama      Jenis   Cosine Similarity Score
50               Miracle Oil Serum  Face Serum                 0.193084
49       HydraMax Water Bank Serum  Face Serum                 0.142846
52    Retinol Smooth Glowing Serum  Face Serum                 0.132777
47       AHA-BHA-PHA Peeling Serum  Face Serum                 0.131798
45  Tremella Daily Hydrating Serum  Face Serum                 0.125716

Face Serum Kering Kusam Retinol, Glycerin, Hyaluronic Acid, Ceramide, Alpha Hydroxy Acid (AHA)
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
52       Retinol Smooth Glowing Serum  Face Serum                 0.302674
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.183495
49          HydraMax Water Bank Serum  Face Serum                 0.164577
54  Daily Defender Multivitamin Serum  Face Serum                 0.134170
45     Tremella Daily Hydrating Serum  Face Serum                 0.133161

Face Serum Kering Jerawat Azelaic Acid, Salicylic Acid, Glycerin, Hyaluronic Acid, Benzoyl Peroxide
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.295060
54  Daily Defender Multivitamin Serum  Face Serum                 0.136776
42                    Acne Care Serum  Face Serum                 0.134827
56                Centella Herb Serum  Face Serum                 0.132763
57   AcnePlus Complete Solution Serum  Face Serum                 0.126680

Face Serum Kombinasi Normal Niacinamide, Vitamin C, Glycerin, Hyaluronic Acid, Salicylic Acid
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.287154
54  Daily Defender Multivitamin Serum  Face Serum                 0.187576
55           Niacinamide Skin Booster  Face Serum                 0.176987
56                Centella Herb Serum  Face Serum                 0.161089
57   AcnePlus Complete Solution Serum  Face Serum                 0.158120

Face Serum Kombinasi Kusam Retinol, Alpha Hydroxy Acid (AHA), Vitamin C, Hyaluronic Acid, Glycerin
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
52       Retinol Smooth Glowing Serum  Face Serum                 0.239108
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.175066
54  Daily Defender Multivitamin Serum  Face Serum                 0.128006
49          HydraMax Water Bank Serum  Face Serum                 0.117048
57   AcnePlus Complete Solution Serum  Face Serum                 0.100192

Face Serum Kombinasi Jerawat Azelaic Acid, Salicylic Acid, Niacinamide, Retinol, Vitamin C
Face Serum

                                    Nama      Jenis   Cosine Similarity Score
47             AHA-BHA-PHA Peeling Serum  Face Serum                 0.270697
52          Retinol Smooth Glowing Serum  Face Serum                 0.268111
59  Niacinamide - Brightening Serum 20ml  Face Serum                 0.154055
56                   Centella Herb Serum  Face Serum                 0.151025
42                       Acne Care Serum  Face Serum                 0.137383

Moisturizer Normal Normal Glycerin, Ceramide, Cholesterol, Cortisol, Urea
Moisturizer

,Nama,Jenis,Cosine Similarity Score
63,Daily Light Moisturizer,Moisturizer,0.199134
67,Skin Oasis Barrier,Moisturizer,0.163655
66,Dew Calm Down Gel,Moisturizer,0.153486
68,Acneact Gentle Acne Moisturizer,Moisturizer,0.138396
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.130936

Moisturizer Normal Kusam Retinol, Alpha Hydroxy Acid (AHA), Niacinamide, Vitamin C, Licorice Root Extract
Moisturizer

,Nama,Jenis,Cosine Similarity Score
60,Licorice Creamy Light Moisturizer,Moisturizer,0.182869
73,AcnePlus Skin Defense Moisturizer,Moisturizer,0.135581
71,Skin Goals Moisture Silk Creme,Moisturizer,0.134016
62,24-Hour Hydro Surge Moisturizer,Moisturizer,0.122706
70,Oil Free Brightening Daily Moisturizer,Moisturizer,0.105387

Moisturizer Normal Jerawat Niacinamide, Ceramide, Lactic Acid, Azelaic Acid, Retinoid
Moisturizer

,Nama,Jenis,Cosine Similarity Score
63,Daily Light Moisturizer,Moisturizer,0.200017
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.190831
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.171629
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.156112
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.154895

Moisturizer Berminyak Normal Niacinamide, Hyaluronic Acid, Glycerin, Niacinamide, Retinol
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.179370
70,Oil Free Brightening Daily Moisturizer,Moisturizer,0.155053
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.154235
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.141205
60,Licorice Creamy Light Moisturizer,Moisturizer,0.129150

Moisturizer Berminyak Kusam Glycerin, Retinol, Alpha Hydroxy Acids (AHA), Niacinamide, Vitamin C
Moisturizer

,Nama,Jenis,Cosine Similarity Score
70,Oil Free Brightening Daily Moisturizer,Moisturizer,0.091883
60,Licorice Creamy Light Moisturizer,Moisturizer,0.062870
66,Dew Calm Down Gel,Moisturizer,0.048482
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.047383
68,Acneact Gentle Acne Moisturizer,Moisturizer,0.045124

Moisturizer Berminyak Jerawat Lactic Acid, Retinol, Azelaic Acid, Niacinamide, Salicylic Acid
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.180207
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.178931
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.173783
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.156849
68,Acneact Gentle Acne Moisturizer,Moisturizer,0.117835

Moisturizer Kering Normal Hyaluronic Acid, Ceramide, Glycerin, Centella Asiatica, Squalene
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.216188
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.212529
70,Oil Free Brightening Daily Moisturizer,Moisturizer,0.200612
77,Aquabloom Moisturizer,Moisturizer,0.186991
63,Daily Light Moisturizer,Moisturizer,0.150682

Moisturizer Kering Kusam Glycerin, Alpha Hydroxy Acid (AHA), Retinol, Vitamin C, Hyaluronic Acid
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.178508
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.145514
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.130535
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.125983
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.082826

Moisturizer Kering Jerawat Glycerin, Azelaic Acid, Salicylic Acid, Niacinamide, Retinol
Moisturizer

,Nama,Jenis,Cosine Similarity Score
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.150390
68,Acneact Gentle Acne Moisturizer,Moisturizer,0.128065
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.125586
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.116730
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.113575

Moisturizer Kombinasi Normal Niacinamide, Glycerin, Centella Asiatica, Hyaluronic Acid, Vitamin C
Moisturizer

,Nama,Jenis,Cosine Similarity Score
70,Oil Free Brightening Daily Moisturizer,Moisturizer,0.243535
77,Aquabloom Moisturizer,Moisturizer,0.186617
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.178965
73,AcnePlus Skin Defense Moisturizer,Moisturizer,0.168737
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.153887

Moisturizer Kombinasi Kusam Retinol, Alpha Hydroxy Acid (AHA), Niacinamide, Vitamin C, Glycerin
Moisturizer

,Nama,Jenis,Cosine Similarity Score
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.101432
70,Oil Free Brightening Daily Moisturizer,Moisturizer,0.099438
60,Licorice Creamy Light Moisturizer,Moisturizer,0.086935
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.075569
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.065795

Moisturizer Kombinasi Jerawat Retinol, Niacinamide, Azelaic Acid, Salicylic Acid, Tea Tree Oil
Moisturizer

,Nama,Jenis,Cosine Similarity Score
70,Oil Free Brightening Daily Moisturizer,Moisturizer,0.118344
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.116384
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.114402
68,Acneact Gentle Acne Moisturizer,Moisturizer,0.097490
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.096549

Sunscreen Normal Normal Titanium Dioxide, Methoxycinnamate, Zinc Oxide, Octocrylene, Cyclopentasiloxane
Sunscreen

,Nama,Jenis,Cosine Similarity Score
90,Skin Barrier Sunscreen SPF 50 PA++++,Sunscreen,0.285655
91,Bb Size SPF 50+ PA++ - Skin Pretty Filter,Sunscreen,0.186124
82,Supreme Hybrid Sun Stick SPF 50+ PA++++,Sunscreen,0.146964
99,Perfect Shield Sunscreen Normal To Dry Skin Spf 30/Pa++,Sunscreen,0.145899
92,Cloud Sunscreen,Sunscreen,0.132028

Sunscreen Berminyak Normal Niacinamide, Methoxycinnamate, Titanium Dioxide, Tea Tree Oil, Iron Oxide
Sunscreen

,Nama,Jenis,Cosine Similarity Score
80,No Sebum Mineral Blur Translucent Loose Powder SPF39 PA++++,Sunscreen,0.215664
89,Brighter Sun-Day SPF 50 PA++,Sunscreen,0.212071
82,Supreme Hybrid Sun Stick SPF 50+ PA++++,Sunscreen,0.175397
90,Skin Barrier Sunscreen SPF 50 PA++++,Sunscreen,0.162004
84,Cera Sunscreen,Sunscreen,0.132938

Sunscreen Kering Normal Glycerin, Hyaluronic Acid, Zinc Oxide, Titanium Dioxide, Capric Triglyceride
Sunscreen

                                    Nama     Jenis   Cosine Similarity Score
90  Skin Barrier Sunscreen SPF 50 PA++++  Sunscreen                 0.267105
96      Tone Up UV Elixir SPF 50+ PA++++  Sunscreen                 0.186548
86                Block It Out Sunscreen  Sunscreen                 0.178938
97            Hydramax-C Sunscreen Serum  Sunscreen                 0.170054
88            Aqua Sun-Day SPF50+ PA++++  Sunscreen                 0.158188

Sunscreen Kombinasi Normal Titanium Dioxide, Zinc Oxide, Niacinamide, Glycerin, Octocrylene
Sunscreen

,Nama,Jenis,Cosine Similarity Score
90,Skin Barrier Sunscreen SPF 50 PA++++,Sunscreen,0.311788
84,Cera Sunscreen,Sunscreen,0.201216
87,Bodyguard Moisturiser Sunscreen Serum,Sunscreen,0.148982
91,Bb Size SPF 50+ PA++ - Skin Pretty Filter,Sunscreen,0.133505
89,Brighter Sun-Day SPF 50 PA++,Sunscreen,0.124372

In [ ]:
for i in range (0,10):
  print(data_pengguna['input'][i]) 

  test_case = data_pengguna['input'][i]

  # TFIDF
  vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))

  the_data = data_product

  if (test_case.find('Facial Wash')!=-1):
    print ('Facial Wash')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][0:20])
    the_product = the_data[0:20]
  elif (test_case.find('Face Toner')!=-1):
    print ('Face Toner')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][20:40])
    the_product = the_data[20:40]
  elif (test_case.find('Face Serum')!=-1):
    print('Face Serum')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][40:60])
    the_product = the_data[40:60]
  elif (test_case.find('Moisturizer')!=-1):
    print('Moisturizer')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][60:80])
    the_product = the_data[60:80]
  else :
    print('Sunscreen')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][80:100])
    the_product = the_data[80:100]
    

  user_input = text_pre_input(test_case)
  index, top5 = get_recommendations_product(user_input, tfidf_dataset1)

  res_data = pd.DataFrame(the_product[['Nama', 'Jenis ']].iloc[index])
  top5.index = res_data.index
  fix_res = pd.concat([res_data, top5], axis=1)
  display(fix_res)

Facial Wash Normal Normal
Facial Wash

                                  Nama       Jenis   cosine similarity score
10              Kind Facial Wash 120ml  Facial Wash                 0.162154
17        Hydralife Mild Cleanser Foam  Facial Wash                 0.114029
11  Facial Wash Gel (Sabun Wajah) Rose  Facial Wash                 0.095287
18      Acne Buster Mild Cleanser Foam  Facial Wash                 0.084831
13      Skin Barrier Face Gel Cleanser  Facial Wash                 0.080023

Facial Wash Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.046538
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.045165
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.042157
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.040064
8,Simply Bright Facial Wash Grape & Hyaluronic Acid,Facial Wash,0.039803

Facial Wash Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.091175
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.086123
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.080530
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.068600
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.065661

Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.097858
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.093268
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.082017
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.080836
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.074898

Facial Wash Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.069756
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.061910
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.054524
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.053671
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.049270

Facial Wash Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.089499
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.088980
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.074133
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.071054
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.067337

Facial Wash Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.093218
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.085364
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.083971
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.072789
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.072012

Facial Wash Kering Kusam Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.061851
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.060622
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.055608
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.052152
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.051387

Facial Wash Kering Jerawat Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.090895
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.090677
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.081527
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.080664
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.067285

Facial Wash Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.100006
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.071306
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.070088
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.068848
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.067637