# IMPORT DATA

In [4]:
# Mengakses google drive 
# from google.colab import drive
# drive.mount('/content/drive')

In [5]:
#library untuk membuat, mengubah dan mengecek data pada tabel
import pandas as pd
pd.set_option('display.max_colwidth', 200)
import numpy as np
#Membaca data csv
data_path = "C:\\Users\\HP\\Downloads\\TUGAS AKHIR\EXCEL KODINGAN\\DataProdukVers5.csv"
data_product = pd.read_csv(data_path)

#Menampilkan data
data_product.head(1)

,No,Nama,Jenis,Merk,Jenis Kulit,Permasalahan Kulit,Deskripsi,Kandungan,Gambar
0,1,Marigold Deep-Cleanse Facial Wash,Facial Wash,NPure,"normal, berminyak, kering, kombinasi","normal, kusam","Pembersih muka dengan busa lembut yang memiliki kandungan Ekstrak Marigold dan 8X Essential Vitamins yang dapat membersihkan kulit dari polusi debu dan kotoran. Diperkaya dengan 5X Peptides, Adeno...","Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glycinate, Calendula Officinalis Flower Extract, Butylene Glycol, Palmitoyl Tripeptide-5, Palmitoyl Te...",https://www.beautyhaul.com/assets/uploads/products/thumbs/800x800/NPURE_Marigold_Deep-Cleanse_Facial_Wash_100gr.webp

# TEXT PREPROCESSING

In [6]:
#Drop kolom yang tidak dibutuhkan
data_product = data_product.drop(labels=["No","Merk","Deskripsi","Gambar"], axis='columns')

data_product.head(5)

,Nama,Jenis,Jenis Kulit,Permasalahan Kulit,Kandungan
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,"normal, berminyak, kering, kombinasi","normal, kusam","Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glycinate, Calendula Officinalis Flower Extract, Butylene Glycol, Palmitoyl Tripeptide-5, Palmitoyl Te..."
1,Acne Facial Wash,Facial Wash,"normal, berminyak, kombinasi","normal, kusam","Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg-40 Hydrogenated Castor Oil, Cocamidopropyl Betaine, Phenoxyethanol, Aminomethyl Propanol, Sodium Chloride, Citrus Limon (..."
2,Hy! Amino Wow-tery Hydrating Facial Wash,Facial Wash,"normal, kering","normal, kusam","Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, Decyl Glucoside, Phenoxyethanol, Potassium Laureth Phosphate, PEG-7..."
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,"normal, berminyak, kering","normal, jerawat, kusam","Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, Decyl Glucoside, Phenoxyethanol, Sodium Benzoate, Potassium Laureth..."
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,kering,kusam,"Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, Decyl Glucoside, Potassium Laureth Phosphate, Distearyl Phthalic Ac..."

In [7]:
data_product.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Nama                100 non-null    object
 1   Jenis               100 non-null    object
 2   Jenis Kulit         100 non-null    object
 3   Permasalahan Kulit  100 non-null    object
 4   Kandungan           100 non-null    object
dtypes: object(5)
memory usage: 4.0+ KB

In [8]:
data_textPre = pd.DataFrame()
data_textPre['data awal'] = data_product['Nama'] + " " + data_product['Jenis '] + " " + data_product['Jenis Kulit'] + " " + data_product['Permasalahan Kulit'] + " " + data_product['Kandungan']

In [9]:
data_textPre[['data awal']].head(5)

                                                                                                                                                                                                 data awal
0  Marigold Deep-Cleanse Facial Wash Facial Wash normal, berminyak, kering, kombinasi normal, kusam Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glyci...
1  Acne Facial Wash Facial Wash normal, berminyak, kombinasi normal, kusam Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg-40 Hydrogenated Castor Oil, Cocamidopropyl Betain...
2  Hy! Amino Wow-tery Hydrating Facial Wash Facial Wash normal, kering normal, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glyc...
3  Hy! Amino Ac-TtackAnti-Acne Facial Wash Facial Wash normal, berminyak, kering normal, jerawat, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, So...
4  Hy! Amino Control Oil Control Facial Wash Facial Wash kering kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, ...



## CASE FOLDING

In [10]:
data_textPre['case folding'] = data_textPre['data awal']
#Case Folding
for i in range (0, len(data_textPre)):
  data_textPre['case folding'][i] = data_textPre['case folding'][i].lower()

In [11]:
data_textPre[['case folding']].head(5)

                                                                                                                                                                                              case folding
0  marigold deep-cleanse facial wash facial wash normal, berminyak, kering, kombinasi normal, kusam water, glycerin, coco-betaine, disodium cocoamphodiacetate, sodium chloride, potassium cocoyl glyci...
1  acne facial wash facial wash normal, berminyak, kombinasi normal, kusam aqua, lauryl glucoside, acrylates copolymer, sodium cocoyl glyrcinate, peg-40 hydrogenated castor oil, cocamidopropyl betain...
2  hy! amino wow-tery hydrating facial wash facial wash normal, kering normal, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glyc...
3  hy! amino ac-ttackanti-acne facial wash facial wash normal, berminyak, kering normal, jerawat, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, so...
4  hy! amino control oil control facial wash facial wash kering kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glycol distearate, ...

In [12]:
data_textPre.head(5)

,data awal,case folding
0,"Marigold Deep-Cleanse Facial Wash Facial Wash normal, berminyak, kering, kombinasi normal, kusam Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glyci...","marigold deep-cleanse facial wash facial wash normal, berminyak, kering, kombinasi normal, kusam water, glycerin, coco-betaine, disodium cocoamphodiacetate, sodium chloride, potassium cocoyl glyci..."
1,"Acne Facial Wash Facial Wash normal, berminyak, kombinasi normal, kusam Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg-40 Hydrogenated Castor Oil, Cocamidopropyl Betain...","acne facial wash facial wash normal, berminyak, kombinasi normal, kusam aqua, lauryl glucoside, acrylates copolymer, sodium cocoyl glyrcinate, peg-40 hydrogenated castor oil, cocamidopropyl betain..."
2,"Hy! Amino Wow-tery Hydrating Facial Wash Facial Wash normal, kering normal, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glyc...","hy! amino wow-tery hydrating facial wash facial wash normal, kering normal, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glyc..."
3,"Hy! Amino Ac-TtackAnti-Acne Facial Wash Facial Wash normal, berminyak, kering normal, jerawat, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, So...","hy! amino ac-ttackanti-acne facial wash facial wash normal, berminyak, kering normal, jerawat, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, so..."
4,"Hy! Amino Control Oil Control Facial Wash Facial Wash kering kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, ...","hy! amino control oil control facial wash facial wash kering kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glycol distearate, ..."

## TOKENIZING

In [13]:
pip install nltk

Requirement already satisfied: nltk in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (3.8.1)
Requirement already satisfied: click in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from nltk) (8.1.3)
Requirement already satisfied: joblib in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from nltk) (1.2.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from nltk) (2023.3.23)
Requirement already satisfied: tqdm in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from nltk) (4.65.0)
Requirement already satisfied: colorama in c:\users\hp\appdata\roaming\python\python38\site-packages (from click->nltk) (0.4.4)
Note: you may need to restart the kernel to use updated packages.

In [14]:
#Mengimport nltk
import nltk
#Mendownload package untuk menghapus tanda baca
nltk.download('punkt')

#import reguler expression
import re
#import string
import string

# impor word_tokenize dari modul nltk
from nltk.tokenize import word_tokenize

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

In [15]:
#Tokenizing
data_textPre['tokenizing'] = data_textPre['case folding']

for i in range (0, len(data_textPre)):
  #Menghapus Angka
  data_textPre['tokenizing'][i] = re.sub(r"\d+", "", data_textPre['tokenizing'][i])
  #Menghapus Tanda Baca
  data_textPre['tokenizing'][i] = data_textPre['tokenizing'][i].translate(str.maketrans('','',string.punctuation))
  #Menghapus Simbol (@)
  data_textPre['tokenizing'][i] = re.sub(r"@\S+", "", data_textPre['tokenizing'][i])
  #Menghapus URL
  data_textPre['tokenizing'][i] = re.sub("http[s]?\://\S+","",data_textPre['tokenizing'][i])
  #Menghapus tab atau line karakter
  data_textPre['tokenizing'][i] = re.sub(r"\n", "", data_textPre['tokenizing'][i])
  #Menghapus single alpabet
  data_textPre['tokenizing'][i] = re.sub(r"\b[a-zA-Z]\b","",data_textPre['tokenizing'][i])
  #Menghapus berlebihan spasi
  data_textPre['tokenizing'][i] = re.sub('\s+',' ',data_textPre['tokenizing'][i])
  #Memisahkan kata menggunakan word_tokenize
  data_textPre['tokenizing'][i] = nltk.word_tokenize(data_textPre['tokenizing'][i])

In [16]:
data_textPre[['tokenizing']].head(5)

                                                                                                                                                                                                tokenizing
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, cocoamphodiacetate, sodium, chloride, potassium, co...
1  [acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidop...
2  [hy, amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium,...
3  [hy, amino, acttackantiacne, facial, wash, facial, wash, normal, berminyak, kering, normal, jerawat, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekke...
4  [hy, amino, control, oil, control, facial, wash, facial, wash, kering, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chloride, gl...

In [17]:
data_textPre

,data awal,case folding,tokenizing
0,"Marigold Deep-Cleanse Facial Wash Facial Wash normal, berminyak, kering, kombinasi normal, kusam Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glyci...","marigold deep-cleanse facial wash facial wash normal, berminyak, kering, kombinasi normal, kusam water, glycerin, coco-betaine, disodium cocoamphodiacetate, sodium chloride, potassium cocoyl glyci...","[marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, cocoamphodiacetate, sodium, chloride, potassium, co..."
1,"Acne Facial Wash Facial Wash normal, berminyak, kombinasi normal, kusam Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg-40 Hydrogenated Castor Oil, Cocamidopropyl Betain...","acne facial wash facial wash normal, berminyak, kombinasi normal, kusam aqua, lauryl glucoside, acrylates copolymer, sodium cocoyl glyrcinate, peg-40 hydrogenated castor oil, cocamidopropyl betain...","[acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidop..."
2,"Hy! Amino Wow-tery Hydrating Facial Wash Facial Wash normal, kering normal, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glyc...","hy! amino wow-tery hydrating facial wash facial wash normal, kering normal, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glyc...","[hy, amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium,..."
3,"Hy! Amino Ac-TtackAnti-Acne Facial Wash Facial Wash normal, berminyak, kering normal, jerawat, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, So...","hy! amino ac-ttackanti-acne facial wash facial wash normal, berminyak, kering normal, jerawat, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, so...","[hy, amino, acttackantiacne, facial, wash, facial, wash, normal, berminyak, kering, normal, jerawat, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekke..."
4,"Hy! Amino Control Oil Control Facial Wash Facial Wash kering kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, ...","hy! amino control oil control facial wash facial wash kering kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glycol distearate, ...","[hy, amino, control, oil, control, facial, wash, facial, wash, kering, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chloride, gl..."
...,...,...,...
95,"Holyshield! UV Watery Sunscreen Gel SPF 50+ PA++++ Sunscreen normal, berminyak, kering, kombinasi normal Aqua Ethylhexyl Methoxycinnamate Butylene Glycol Butyl Methoxydibenzoylmethane Octocrylene ...","holyshield! uv watery sunscreen gel spf 50+ pa++++ sunscreen normal, berminyak, kering, kombinasi normal aqua ethylhexyl methoxycinnamate butylene glycol butyl methoxydibenzoylmethane octocrylene ...","[holyshield, uv, watery, sunscreen, gel, spf, pa, sunscreen, normal, berminyak, kering, kombinasi, normal, aqua, ethylhexyl, methoxycinnamate, butylene, glycol, butyl, methoxydibenzoylmethane, oct..."
96,"Tone Up UV Elixir SPF 50+ PA++++ Sunscreen normal, berminyak, kering, kombinasi normal Hyaluronic Acid , Sunflower Seed Oil, Bisabolol","tone up uv elixir spf 50+ pa++++ sunscreen normal, berminyak, kering, kombinasi normal hyaluronic acid , sunflower seed oil, bisabolol","[tone, up, uv, elixir, spf, pa, sunscreen, normal, berminyak, kering, kombinasi, normal, hyaluronic, acid, sunflower, seed, oil, bisabolol]"
97,"Hydramax-C Sunscreen Serum Sunscreen normal, berminyak, kering, kombinasi normal Aqua Ethylhexyl Methoxycinnamate Butyl Methoxydibenzoylmethane Glycerin* Propanediol* Polymethyl Methacrylate Octoc...","hydramax-c sunscreen serum sunscreen normal, berminyak, kering, kombinasi normal aqua ethylhexyl methoxycinnamate butyl methoxydibenzoylmethane glycerin* propanediol* polymethyl methacrylate octoc...","[hydramaxc, sunscreen, serum, sunscreen, normal, berminyak, kering, kombinasi, normal, aqua, ethylhexyl, methoxycinnamate, butyl, methoxydibenzoylmethane, glycerin, propanediol, polymethyl, methac..."
98,"Hydrasoothe Sunscreen Gel SPF45+++ Sunscreen normal, berminyak, kering, kombinasi normal Aqua Glycerin Propanediol Ethylhexyl Methoxycinnamate Butyl Methoxydibenzoylmethane portulaca oleracea extr...","hydrasoothe sunscreen gel spf45+++ sunscreen normal, berminyak, kering, kombinasi normal aqua glycerin propanediol ethylhexyl methoxycinnamate butyl methoxydibenzoylmethane portulaca oleracea extr...","[hydrasoothe, sunscreen, gel, spf, sunscreen, normal, berminyak, kering, kombinasi, normal, aqua, glycerin, propanediol, ethylhexyl, methoxycinnamate, butyl, methoxydibenzoylmethane, portulaca, ol..."
99,"Perfect Shield Sunscreen Normal To Dry Skin Spf 30/Pa++ Sunscreen normal, kering normal Chemical Sunscreen (UVA & UVB Filter): Ethylhexyl Salicylate, Ethylhexyl Methoxycinnamate, Phenylbenzimidazo...","perfect shield sunscreen normal to dry skin spf 30/pa++ sunscreen normal, kering normal chemical sunscreen (uva & uvb filter): ethylhexyl salicylate, ethylhexyl methoxycinnamate, phenylbenzimidazo...","[perfect, shield, sunscreen, normal, to, dry, skin, spf, pa, sunscreen, normal, kering, normal, chemical, sunscreen, uva, uvb, filter, ethylhexyl, salicylate, ethylhexyl, methoxycinnamate, phenylb..."

## FILTERING

In [18]:
#Filtering
data_textPre['filtering'] = data_textPre['tokenizing']

#Mendownload package stopwords untuk menghapus kata kata yang tidak berarti dalam sebuah kalimat
nltk.download('stopwords')
from nltk.corpus import stopwords

#Stopword Bahasa Indonesia
indo_stopword = (stopwords.words('indonesian'))

#Stopword Bahasa Inggris
eng_stopword = (stopwords.words('english'))

#Data Stopword
data_stopword = indo_stopword
data_stopword.extend(eng_stopword)
data_stopword = str(data_stopword)
# display(data_stopword)

for i in range (0, len(data_textPre['filtering'])):

  data_textPre['filtering'][i] = [word for word in data_textPre['filtering'][i] if not word in (data_stopword)]

data_filtering = pd.DataFrame(data_textPre['filtering'])

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\HP\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [19]:
data_textPre[['filtering']].head(5)
# data_filtering.head(5)

                                                                                                                                                                                                 filtering
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, cocoamphodiacetate, sodium, chloride, potassium, co...
1  [acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidop...
2  [amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chl...
3  [amino, acttackantiacne, facial, wash, facial, wash, normal, berminyak, kering, normal, jerawat, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, s...
4  [amino, control, oil, control, facial, wash, facial, wash, kering, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chloride, glycol...

In [20]:
data_textPre

,data awal,case folding,tokenizing,filtering
0,"Marigold Deep-Cleanse Facial Wash Facial Wash normal, berminyak, kering, kombinasi normal, kusam Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glyci...","marigold deep-cleanse facial wash facial wash normal, berminyak, kering, kombinasi normal, kusam water, glycerin, coco-betaine, disodium cocoamphodiacetate, sodium chloride, potassium cocoyl glyci...","[marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, cocoamphodiacetate, sodium, chloride, potassium, co...","[marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, cocoamphodiacetate, sodium, chloride, potassium, co..."
1,"Acne Facial Wash Facial Wash normal, berminyak, kombinasi normal, kusam Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg-40 Hydrogenated Castor Oil, Cocamidopropyl Betain...","acne facial wash facial wash normal, berminyak, kombinasi normal, kusam aqua, lauryl glucoside, acrylates copolymer, sodium cocoyl glyrcinate, peg-40 hydrogenated castor oil, cocamidopropyl betain...","[acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidop...","[acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidop..."
2,"Hy! Amino Wow-tery Hydrating Facial Wash Facial Wash normal, kering normal, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glyc...","hy! amino wow-tery hydrating facial wash facial wash normal, kering normal, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glyc...","[hy, amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium,...","[amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chl..."
3,"Hy! Amino Ac-TtackAnti-Acne Facial Wash Facial Wash normal, berminyak, kering normal, jerawat, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, So...","hy! amino ac-ttackanti-acne facial wash facial wash normal, berminyak, kering normal, jerawat, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, so...","[hy, amino, acttackantiacne, facial, wash, facial, wash, normal, berminyak, kering, normal, jerawat, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekke...","[amino, acttackantiacne, facial, wash, facial, wash, normal, berminyak, kering, normal, jerawat, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, s..."
4,"Hy! Amino Control Oil Control Facial Wash Facial Wash kering kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, ...","hy! amino control oil control facial wash facial wash kering kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glycol distearate, ...","[hy, amino, control, oil, control, facial, wash, facial, wash, kering, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chloride, gl...","[amino, control, oil, control, facial, wash, facial, wash, kering, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chloride, glycol..."
...,...,...,...,...
95,"Holyshield! UV Watery Sunscreen Gel SPF 50+ PA++++ Sunscreen normal, berminyak, kering, kombinasi normal Aqua Ethylhexyl Methoxycinnamate Butylene Glycol Butyl Methoxydibenzoylmethane Octocrylene ...","holyshield! uv watery sunscreen gel spf 50+ pa++++ sunscreen normal, berminyak, kering, kombinasi normal aqua ethylhexyl methoxycinnamate butylene glycol butyl methoxydibenzoylmethane octocrylene ...","[holyshield, uv, watery, sunscreen, gel, spf, pa, sunscreen, normal, berminyak, kering, kombinasi, normal, aqua, ethylhexyl, methoxycinnamate, butylene, glycol, butyl, methoxydibenzoylmethane, oct...","[holyshield, uv, watery, sunscreen, gel, spf, sunscreen, normal, berminyak, kering, kombinasi, normal, aqua, ethylhexyl, methoxycinnamate, butylene, glycol, butyl, methoxydibenzoylmethane, octocry..."
96,"Tone Up UV Elixir SPF 50+ PA++++ Sunscreen normal, berminyak, kering, kombinasi normal Hyaluronic Acid , Sunflower Seed Oil, Bisabolol","tone up uv elixir spf 50+ pa++++ sunscreen normal, berminyak, kering, kombinasi normal hyaluronic acid , sunflower seed oil, bisabolol","[tone, up, uv, elixir, spf, pa, sunscreen, normal, berminyak, kering, kombinasi, normal, hyaluronic, acid, sunflower, seed, oil, bisabolol]","[tone, uv, elixir, spf, sunscreen, normal, berminyak, kering, kombinasi, normal, hyaluronic, acid, sunflower, seed, oil, bisabolol]"
97,"Hydramax-C Sunscreen Serum Sunscreen normal, berminyak, kering, kombinasi normal Aqua Ethylhexyl Methoxycinnamate Butyl Methoxydibenzoylmethane Glycerin* Propanediol* Polymethyl Methacrylate Octoc...","hydramax-c sunscreen serum sunscreen normal, berminyak, kering, kombinasi normal aqua ethylhexyl methoxycinnamate butyl methoxydibenzoylmethane glycerin* propanediol* polymethyl methacrylate octoc...","[hydramaxc, sunscreen, serum, sunscreen, normal, berminyak, kering, kombinasi, normal, aqua, ethylhexyl, methoxycinnamate, butyl, methoxydibenzoylmethane, glycerin, propanediol, polymethyl, methac...","[hydramaxc, sunscreen, serum, sunscreen, normal, berminyak, kering, kombinasi, normal, aqua, ethylhexyl, methoxycinnamate, butyl, methoxydibenzoylmethane, glycerin, propanediol, polymethyl, methac..."
98,"Hydrasoothe Sunscreen Gel SPF45+++ Sunscreen normal, berminyak, kering, kombinasi normal Aqua Glycerin Propanediol Ethylhexyl Methoxycinnamate Butyl Methoxydibenzoylmethane portulaca oleracea extr...","hydrasoothe sunscreen gel spf45+++ sunscreen normal, berminyak, kering, kombinasi normal aqua glycerin propanediol ethylhexyl methoxycinnamate butyl methoxydibenzoylmethane portulaca oleracea extr...","[hydrasoothe, sunscreen, gel, spf, sunscreen, normal, berminyak, kering, kombinasi, normal, aqua, glycerin, propanediol, ethylhexyl, methoxycinnamate, butyl, methoxydibenzoylmethane, portulaca, ol...","[hydrasoothe, sunscreen, gel, spf, sunscreen, normal, berminyak, kering, kombinasi, normal, aqua, glycerin, propanediol, ethylhexyl, methoxycinnamate, butyl, methoxydibenzoylmethane, portulaca, ol..."
99,"Perfect Shield Sunscreen Normal To Dry Skin Spf 30/Pa++ Sunscreen normal, kering normal Chemical Sunscreen (UVA & UVB Filter): Ethylhexyl Salicylate, Ethylhexyl Methoxycinnamate, Phenylbenzimidazo...","perfect shield sunscreen normal to dry skin spf 30/pa++ sunscreen normal, kering normal chemical sunscreen (uva & uvb filter): ethylhexyl salicylate, ethylhexyl methoxycinnamate, phenylbenzimidazo...","[perfect, shield, sunscreen, normal, to, dry, skin, spf, pa, sunscreen, normal, kering, normal, chemical, sunscreen, uva, uvb, filter, ethylhexyl, salicylate, ethylhexyl, methoxycinnamate, phenylb...","[perfect, shield, sunscreen, normal, dry, skin, spf, sunscreen, normal, kering, normal, chemical, sunscreen, uva, uvb, filter, ethylhexyl, salicylate, ethylhexyl, methoxycinnamate, phenylbenzimida..."

## STEMMING

In [21]:
pip install PySastrawi

Requirement already satisfied: PySastrawi in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (1.2.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
data_textPre['stemming'] = data_filtering
#Stemming
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

#Membuat stemmer
Factory = StemmerFactory()
Stemmer = Factory.create_stemmer()

for i in range (0, len(data_textPre)):
  temp = []
  for j in range (0, len(data_textPre['stemming'][i])):
    data_textPre['stemming'][i][j]= Stemmer.stem(data_textPre['stemming'][i][j])
    temp.append(data_textPre['stemming'][i][j])
  data_textPre['stemming'][i] = temp

In [23]:
data_textPre[['stemming']].head(5)

                                                                                                                                                                                                  stemming
0  [marigold, deepcleanse, facial, wash, facial, wash, normal, minyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, sodium, cocoamphodiacetate, sodium, chloride, potassium, cocoyl,...
1  [acne, facial, wash, facial, wash, normal, minyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidoprop...
2  [amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chl...
3  [amino, acttackantiacne, facial, wash, facial, wash, normal, minyak, kering, normal, jerawat, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, soji...
4  [amino, control, oil, control, facial, wash, facial, wash, kering, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chloride, glycol...

In [24]:
data_textPre.head(5)

,data awal,case folding,tokenizing,filtering,stemming
0,"Marigold Deep-Cleanse Facial Wash Facial Wash normal, berminyak, kering, kombinasi normal, kusam Water, Glycerin, Coco-Betaine, Disodium Cocoamphodiacetate, Sodium Chloride, Potassium Cocoyl Glyci...","marigold deep-cleanse facial wash facial wash normal, berminyak, kering, kombinasi normal, kusam water, glycerin, coco-betaine, disodium cocoamphodiacetate, sodium chloride, potassium cocoyl glyci...","[marigold, deepcleanse, facial, wash, facial, wash, normal, berminyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, disodium, cocoamphodiacetate, sodium, chloride, potassium, co...","[marigold, deepcleanse, facial, wash, facial, wash, normal, minyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, sodium, cocoamphodiacetate, sodium, chloride, potassium, cocoyl,...","[marigold, deepcleanse, facial, wash, facial, wash, normal, minyak, kering, kombinasi, normal, kusam, water, glycerin, cocobetaine, sodium, cocoamphodiacetate, sodium, chloride, potassium, cocoyl,..."
1,"Acne Facial Wash Facial Wash normal, berminyak, kombinasi normal, kusam Aqua, Lauryl Glucoside, Acrylates Copolymer, Sodium Cocoyl Glyrcinate, Peg-40 Hydrogenated Castor Oil, Cocamidopropyl Betain...","acne facial wash facial wash normal, berminyak, kombinasi normal, kusam aqua, lauryl glucoside, acrylates copolymer, sodium cocoyl glyrcinate, peg-40 hydrogenated castor oil, cocamidopropyl betain...","[acne, facial, wash, facial, wash, normal, berminyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidop...","[acne, facial, wash, facial, wash, normal, minyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidoprop...","[acne, facial, wash, facial, wash, normal, minyak, kombinasi, normal, kusam, aqua, lauryl, glucoside, acrylates, copolymer, sodium, cocoyl, glyrcinate, peg, hydrogenated, castor, oil, cocamidoprop..."
2,"Hy! Amino Wow-tery Hydrating Facial Wash Facial Wash normal, kering normal, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glyc...","hy! amino wow-tery hydrating facial wash facial wash normal, kering normal, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glyc...","[hy, amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium,...","[amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chl...","[amino, wowtery, hydrating, facial, wash, facial, wash, normal, kering, normal, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chl..."
3,"Hy! Amino Ac-TtackAnti-Acne Facial Wash Facial Wash normal, berminyak, kering normal, jerawat, kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, So...","hy! amino ac-ttackanti-acne facial wash facial wash normal, berminyak, kering normal, jerawat, kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, so...","[hy, amino, acttackantiacne, facial, wash, facial, wash, normal, berminyak, kering, normal, jerawat, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekke...","[amino, acttackantiacne, facial, wash, facial, wash, normal, minyak, kering, normal, jerawat, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, soji...","[amino, acttackantiacne, facial, wash, facial, wash, normal, minyak, kering, normal, jerawat, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, soji..."
4,"Hy! Amino Control Oil Control Facial Wash Facial Wash kering kusam Water, Sodium Laureth Sulfate, Cocamidopropyl Betaine, Sodium Lauryl Sulfate, Sekken Soji-K, Sodium Chloride, Glycol Distearate, ...","hy! amino control oil control facial wash facial wash kering kusam water, sodium laureth sulfate, cocamidopropyl betaine, sodium lauryl sulfate, sekken soji-k, sodium chloride, glycol distearate, ...","[hy, amino, control, oil, control, facial, wash, facial, wash, kering, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chloride, gl...","[amino, control, oil, control, facial, wash, facial, wash, kering, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chloride, glycol...","[amino, control, oil, control, facial, wash, facial, wash, kering, kusam, water, sodium, laureth, sulfate, cocamidopropyl, betaine, sodium, lauryl, sulfate, sekken, sojik, sodium, chloride, glycol..."

In [25]:
data_resTp = data_textPre

In [26]:
#Menjadikan dataset file csv
data_resTp.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/NEW/" +'dataTextPreprocessing.xlsx', index=False)

# Menggabungkan Kata

In [27]:
#Menggabungkan setiap kata dalam satu data
dataset_res = [] 

for i in range (0, len(data_textPre['stemming'])):
  temp = []
  temp = " ".join(data_textPre['stemming'][i])
  dataset_res.append(temp)

dataset = pd.DataFrame(dataset_res, columns=["data"])
dataset

                                                                                                                                                                                                       data
0   marigold deepcleanse facial wash facial wash normal minyak kering kombinasi normal kusam water glycerin cocobetaine sodium cocoamphodiacetate sodium chloride potassium cocoyl glycinate calendula o...
1   acne facial wash facial wash normal minyak kombinasi normal kusam aqua lauryl glucoside acrylates copolymer sodium cocoyl glyrcinate peg hydrogenated castor oil cocamidopropyl betaine phenoxyethan...
2   amino wowtery hydrating facial wash facial wash normal kering normal kusam water sodium laureth sulfate cocamidopropyl betaine sodium lauryl sulfate sekken sojik sodium chloride glycol distearate ...
3   amino acttackantiacne facial wash facial wash normal minyak kering normal jerawat kusam water sodium laureth sulfate cocamidopropyl betaine sodium lauryl sulfate sekken sojik sodium chloride glyco...
4   amino control oil control facial wash facial wash kering kusam water sodium laureth sulfate cocamidopropyl betaine sodium lauryl sulfate sekken sojik sodium chloride glycol distearate decyl glucos...
..                                                                                                                                                                                                      ...
95  holyshield uv watery sunscreen gel spf sunscreen normal minyak kering kombinasi normal aqua ethylhexyl methoxycinnamate butylene glycol butyl methoxydibenzoylmethane octocrylene ammonium polyacryl...
96                                                                                          tone uv elixir spf sunscreen normal minyak kering kombinasi normal hyaluronic acid sunflower seed oil bisabolol
97  hydramaxc sunscreen serum sunscreen normal minyak kering kombinasi normal aqua ethylhexyl methoxycinnamate butyl methoxydibenzoylmethane glycerin propanediol polymethyl methacrylate octocrylene bu...
98  hydrasoothe sunscreen gel spf sunscreen normal minyak kering kombinasi normal aqua glycerin propanediol ethylhexyl methoxycinnamate butyl methoxydibenzoylmethane portulaca oleracea extract sodium ...
99  perfect shield sunscreen normal dry skin spf sunscreen normal kering normal chemical sunscreen uva uvb filter ethylhexyl salicylate ethylhexyl methoxycinnamate phenylbenzimidazole sulfonic acid bu...

[100 rows x 1 columns]

In [28]:
yu = dataset['data'][20:40]
yu
# yu.info()

20    skin bae series toner marine collagen hyacross galactomyces face toner normal minyak kering kombinasi normal kusam water propylene glycol hydrolyzed collagen extract glycerin phenoxyethanol galact...
21    moisture rich hydrating toner face toner normal minyak kering kombinasi normal aqua glycerin lactobacillus collagen mesembryanthemum crystallinum leaf extract ferment lysate pentylene glycol allan...
22    mild purifying toner face toner normal minyak kering kombinasi jerawat aqua glycerin centella asiatica extract succinic acid chlorphenesin xanthan gum phenoxyethanol citric acid allantoin cinnamom...
23    multi acids glowing toner face toner normal minyak kering kombinasi normal kusam aqua glycerin aloe barbadensis leaf juice tranexamic acid chlorphenesin xanthan gum phenoxyethanol citric acid mand...
24    miraculous divine aura essencetoner paola rena face toner normal minyak kering kombinasi normal kusam jerawat aqua niacinamide quartz glycerin oethyl ascorbic acid propylene glycol phenoxyethanol ...
25    miraculous retinol toner face toner normal minyak kering normal kusam jerawat water propylene glycol glycerin phenoxyethanol carbomer peg hydrogenated castor oil capryliccapric triglyceride camell...
26    beneath dear dor essence toner face toner normal minyak kering kombinasi normal kusam water phenyl trimethicone dimethicone niacinamide glycerin olea europaea fruit oil cyclopentasiloxane lactic a...
27    beneath cloud nine essence toner face toner normal minyak kering kombinasi normal kusam jerawat water niacinamide butylene glycol phenoxyethanol ammonium acryloyldimethyltauratevp copolymer allant...
28    skin bae series toner essence vitamin niacinamide carrot exctract raspberry face toner normal minyak kering kombinasi normal kusam aqua glycerin propylene glycol niacinamide oethyl ascorbic acid p...
29    skin bae series toner niacinamide alpha arbutin kale face toner minyak kering normal kusam water propylene glycol niacinamide glycerin alphaarbutin phenoxyethanol hydrolized vegetable protein chlo...
30    skin bae series toner salicylic acid zinc tea tree water face toner normal minyak kering kombinasi normal jerawat water propylene glycol glycerin salicylic acid phenoxyethanol zinc pca melaleuca a...
31    tremella daily hydrating toner face toner normal minyak kering kombinasi normal aqua propanediol niacinamide allantoin panthenol opuntia ficusindica fruit extract sea water peg hydrogenated castor...
32    skin ready hydrating booster face toner normal minyak kering kombinasi normal kusam jerawat water anthemis nobilis flower water niacinamide pentylene glycol aloe barbadensis leaf juice glycerin ph...
33    citrus comb facial toner face toner normal minyak kering kusam aqua propylene glycol ppgbuteth butylene glycol peg hydrogenated castor oil phenoxyethanol glycerin sodium lactate chlorphenesin sodi...
34    berry bounce facial toner face toner normal minyak kering kombinasi normal kusam water butylene glycol glycerin peg dimethicone aloe barbadensis leaf extract portulaca oleracea extract hexanediol ...
35    stay toned balancing essence toner face toner normal minyak kering kombinasi normal kusam water butylene glycol glycerin peg dimethicone aloe barbadensis leaf extract portulaca oleracea extract he...
36    botanical witch hazel toner face toner normal minyak kombinasi normal jerawat aqua hamamelis virginia witch hazel leaf extract glycerin butylene glycol phenoxyethanol peg hydrogenated castor oil t...
37    botanical calendula toner face toner normal minyak kering kombinasi normal kusam aqua butylene glycol sodium pca phenoxyethanol peg hydrogenated castor oil allantoin sodium hyaluronate foeniculum ...
38    purifying hydra toner face toner normal minyak kering kombinasi normal glycerin propanediol camellia sinensis leaf extract hamamelis virginiana witch hazel water brassica oleracea italica broccoli...
39    cica series face toner face toner normal minyak kering kombinasi normal kusam jerawat aqua glycerin propylene glycol niacinamide centella asiatica extract tranexamic acid licorice glycyrrhiza glab...
Name: data, dtype: object

# PERHITUNGAN MANUAL

## MENGHITUNG KAMUS KATA MANUAL

In [29]:
from nltk.tokenize import word_tokenize
##TFIDF MANUAL
word_vocab=[]
for i in range(0,len(dataset)):
  words = dataset['data'][i].split()
  for word in words:
    if word not in word_vocab:
      word_vocab.append(word)

word_vocab = set(word_vocab)
print('total data : ', len(data_textPre))
print('total kata : ', len(word_vocab))

total data :  100
total kata :  1016

In [30]:
# # Melihat adakah perbedaan kamus kata yang dihitung manual dengan menggunakan sklearn
# print(word_vocab)
# tfidf_tokens = set(tfidf_tokens)
# print(tfidf_tokens)
# res= word_vocab.difference(tfidf_tokens)
# print(res)

In [31]:
word_vocab = sorted(set(word_vocab))
print(word_vocab)

['acacia', 'acer', 'acetate', 'acetyl', 'acetylated', 'achillea', 'acid', 'acids', 'acne', 'acneact', 'acnedot', 'acneplus', 'acocia', 'acrylate', 'acrylateacrylic', 'acrylates', 'acrylatesc', 'acrylatesodium', 'acrylatespolytrimethylsiloxymethacrylate', 'acryloyldimethyl', 'acryloyldimethyltauratecarboxyethyl', 'acryloyldimethyltauratevp', 'actinidia', 'acttackantiacne', 'adansonia', 'adenosine', 'adipate', 'age', 'agent', 'ahabhapha', 'alba', 'albatrellus', 'albizia', 'album', 'alcohol', 'alcohols', 'algae', 'algin', 'alginate', 'alkane', 'alkyl', 'allantoin', 'aloe', 'aloevera', 'alpha', 'alphaarbutin', 'alpinum', 'alternafolia', 'alternifolia', 'alumina', 'aluminum', 'amber', 'amide', 'amine', 'amino', 'aminobutanol', 'aminobutyric', 'aminomethyl', 'ammonium', 'amurense', 'angelica', 'angustifolia', 'angustifolium', 'anhydroxylitol', 'annona', 'annuus', 'anthemis', 'antioxidant', 'apple', 'aqua', 'aquabloom', 'arachidyl', 'arachis', 'arbutin', 'arctium', 'argania', 'arginine', 'arisaema', 'artemisia', 'arvensis', 'ascorbate', 'ascorbic', 'ascorbyl', 'asiatic', 'asiatica', 'asiaticoside', 'aspartate', 'aspartic', 'astragalus', 'aura', 'aurantium', 'avena', 'aviculare', 'avocado', 'azadirachta', 'bacillusfolic', 'bacillussoybeanfolic', 'backhouisa', 'bae', 'bakuchiol', 'balancing', 'balm', 'bank', 'barbadensis', 'bark', 'barrier', 'bb', 'beat', 'beeswax', 'beet', 'behenate', 'behenyl', 'beneath', 'benzoate', 'benzoic', 'benzotriazolyl', 'benzyl', 'bergamia', 'bergamot', 'berry', 'beta', 'betaglucan', 'betaine', 'bha', 'bht', 'bicarbonate', 'bifida', 'biome', 'biosaccharide', 'biotin', 'bisabolol', 'bisbenzotriazolyl', 'bisdecyltetradeceth', 'bisdiglyceryl', 'bisethylhexyloxyphenol', 'bisglyceryl', 'bispeg', 'bisulfite', 'block', 'blue', 'blueberry', 'blur', 'bodyguard', 'bomb', 'booster', 'boswellia', 'botanical', 'bounce', 'bran', 'brassica', 'bright', 'brightening', 'brighter', 'brigth', 'bring', 'broccoli', 'buckthorn', 'buster', 'butter', 'butyl', 'butylene', 'butyloctyl', 'butyrospermum', 'caesalpinia', 'caffeine', 'calcium', 'calendula', 'calm', 'calming', 'camellia', 'camphor', 'canina', 'capillaris', 'caprate', 'capric', 'caprylate', 'caprylhydroxamic', 'caprylic', 'capryliccapric', 'capryloyl', 'caprylyl', 'caprylylcapryl', 'carbamate', 'carbanate', 'carbomer', 'carbonate', 'care', 'carica', 'carrot', 'castor', 'cell', 'cellulose', 'centelaasiatica', 'centella', 'cera', 'ceramic', 'ceramide', 'ceresin', 'ceteareth', 'cetearyl', 'ceteraryl', 'ceteth', 'cetyl', 'chamomile', 'chamomilla', 'chebula', 'chemical', 'cherimola', 'chiloensis', 'chinensis', 'chlorantha', 'chlorella', 'chlorhexidine', 'chloride', 'chlorphenesin', 'cholesterol', 'choleth', 'chondrus', 'chromanyl', 'chrysanthemum', 'chrysin', 'cica', 'cinnamomum', 'citrate', 'citric', 'citriodora', 'citrus', 'cleanser', 'cleansing', 'cloud', 'clover', 'cocamide', 'cocamidopropyl', 'coccinia', 'cocoamphodiacetate', 'cocoate', 'cocobetaine', 'cococaprylatecaprate', 'cocoglucoside', 'coconut', 'cocos', 'cocoy', 'cocoyl', 'collagen', 'colloidal', 'comb', 'communis', 'complete', 'complex', 'concentrate', 'confluens', 'control', 'copolymer', 'copper', 'corallina', 'cordyceps', 'corn', 'corymbosum', 'cr', 'cream', 'creamy', 'creatine', 'creme', 'crispus', 'crosspolymer', 'crystallinum', 'cucumber', 'cucumis', 'culture', 'curcuma', 'cyanocobalamin', 'cyclohexasiloxane', 'cyclomethicone', 'cyclopentasiloxane', 'cyclotetrasiloxane', 'cystoseira', 'daily', 'damascena', 'dear', 'decy', 'decyl', 'decylene', 'deep', 'deepcleanse', 'defender', 'defense', 'dehydroacetate', 'dehydroacetic', 'delima', 'deoxyphytantriyl', 'dew', 'diamond', 'dibutyl', 'dicamphor', 'dicaprylatedicaprate', 'dicaprylyl', 'dicetyl', 'diethylamino', 'diethylhexyl', 'digitata', 'digluconate', 'diglycerin', 'diglycidyl', 'diheptanoate', 'dihydroxypropy', 'dihydroxypropyl', 'diisethionate', 'diisostearate', 'dimethicone', 'dimethiconemethicone', 'dimethiconepeg', 'dimethiconevinyl', 'dimethiconol', 'dimethyl', 'dimethylmethoxy', 'dimethylsilanol', 'dioleate', 'dioxide', 'dipentaerythrityl', 'dipeptide', 'diphenylsiloxy', 'dipotassium', 'dipropylene', 'distearate', 'distearyl', 'disuccinate', 'divaricata', 'divine', 'dmdm', 'dodecyl', 'domestica', 'dont', 'dor', 'dpanthenol', 'dream', 'dry', 'dulcis', 'ectoin', 'edta', 'eggplant', 'ekstrak', 'elata', 'elixir', 'enantia', 'eop', 'epilobium', 'essence', 'essencetoner', 'essential', 'ester', 'esters', 'ether', 'ethersodium', 'ethoxydiglycol', 'ethyl', 'ethylenediamine', 'ethylhexanoate', 'ethylhexyglycerin', 'ethylhexyl', 'ethylhexylglycerin', 'europaea', 'exctract', 'expressed', 'extract', 'extracts', 'face', 'facial', 'fagopyrum', 'fennel', 'ferdinandiana', 'ferment', 'ferulic', 'feverfew', 'ficus', 'ficusindica', 'fig', 'filter', 'filtrate', 'flavour', 'florida', 'flour', 'flower', 'flowerleaf', 'flowerleafstem', 'foam', 'foeniculum', 'folic', 'fomes', 'forget', 'fqp', 'fragaria', 'fragrance', 'frangipani', 'free', 'fresh', 'fructooligosaccharides', 'fructose', 'fruit', 'fruitleaf', 'fuciformis', 'full', 'galactomyces', 'galactosyl', 'ganoderma', 'garcinia', 'gardenia', 'gastrodia', 'gel', 'gellan', 'gentle', 'germ', 'gigas', 'ginseng', 'glabra', 'glow', 'glowin', 'glowing', 'glucan', 'gluconate', 'gluconobacterhoney', 'gluconolactone', 'glucose', 'glucoside', 'glutamate', 'glutamine', 'glycereth', 'glycerin', 'glyceryl', 'glycerylnstearate', 'glycinate', 'glycine', 'glycol', 'glycolic', 'glycyrrhiza', 'glycyrrhizate', 'glyrcinate', 'goals', 'gold', 'golden', 'granactive', 'granatum', 'grape', 'gratissima', 'great', 'green', 'guaiazulene', 'guajava', 'guava', 'gum', 'hamamelis', 'hazel', 'hc', 'hcl', 'hditrimethylol', 'helianthus', 'helios', 'herb', 'hexa', 'hexamidine', 'hexanediol', 'hexapeptide', 'hexyl', 'hexylene', 'hexyllactone', 'hexylresorcinol', 'hippophae', 'histidine', 'holyshield', 'honey', 'hops', 'hour', 'humulus', 'hyacross', 'hyaluronate', 'hyaluronatecrosspolymer', 'hyaluronic', 'hybrid', 'hydantoin', 'hydra', 'hydralife', 'hydramax', 'hydramaxc', 'hydrasoothe', 'hydrated', 'hydrating', 'hydro', 'hydrogenated', 'hydrolized', 'hydrolyzed', 'hydroxide', 'hydroxyacetophenone', 'hydroxybenzoyl', 'hydroxydecenoic', 'hydroxyethyl', 'hydroxyethylcellulose', 'hydroxymethylglycinate', 'hydroxypinacolone', 'hydroxypropyl', 'hydroxypropyltrimonium', 'hydroxysultaine', 'hypericum', 'hypogaea', 'idaeus', 'illite', 'indica', 'ingredients', 'ingredientsceramide', 'intense', 'inulin', 'iron', 'isethionate', 'isinonyl', 'isoamyl', 'isododecane', 'isohexadecane', 'isomerate', 'isononanoate', 'isoparaffin', 'isopropyl', 'isosorbide', 'isostearate', 'isotridecyl', 'italica', 'japonica', 'jelly', 'jerawat', 'jojoba', 'juice', 'julibrissin', 'juniperus', 'junos', 'kakadu', 'kale', 'kaolin', 'kering', 'kernel', 'key', 'kind', 'kombinasi', 'kusam', 'kusamjerawat', 'lactate', 'lactic', 'lactobacillus', 'lactobacilluscollagenmesembryanthemum', 'lactobionic', 'lactococcus', 'lactose', 'lactylate', 'lannesiana', 'laurate', 'laureth', 'lauric', 'laurocapram', 'lauroyl', 'lauryl', 'lavandula', 'leaf', 'lecithin', 'lemon', 'lentiscus', 'leontopodium', 'licorice', 'light', 'limon', 'limonene', 'limonum', 'linalool', 'linoleic', 'linolenic', 'lipids', 'liquidum', 'long', 'longa', 'loose', 'lotus', 'lucidum', 'luminous', 'lupulus', 'lysate', 'macadamiate', 'macrocystis', 'madecassic', 'madecassoside', 'magnesium', 'magnolia', 'majus', 'makeup', 'malachite', 'maltodextrin', 'malus', 'mandelic', 'mangostana', 'mannitol', 'marigold', 'marine', 'mask', 'mastic', 'matcha', 'matricaria', 'mays', 'me', 'mea', 'meal', 'medica', 'melaleuca', 'melanin', 'melia', 'melissa', 'melongena', 'membranaceus', 'memory', 'mentha', 'menthol', 'mesembryanthemum', 'methacrylate', 'methicone', 'methoxycinnamate', 'methoxydibenzoylmethane', 'methoxyphenyl', 'methoxysalicylate', 'methyl', 'methylbenzylidene', 'methylcellulose', 'methylchloroisothiazolinone', 'methylene', 'methylglucose', 'methylisothiazolinone', 'methylparaben', 'mica', 'microcrystalline', 'mild', 'milk', 'millefolium', 'mineral', 'minyak', 'miracle', 'miraculous', 'mistletoe', 'moist', 'moisture', 'moisturiser', 'moisturizer', 'moisturizing', 'monostearate', 'moringa', 'morus', 'mousse', 'mulberry', 'multi', 'multivitamin', 'mushroom', 'myristate', 'myristic', 'myristoyl', 'myrtillus', 'naturally', 'nelumbo', 'neopentyl', 'niacinamide', 'night', 'nine', 'nitrate', 'nobilis', 'normal', 'nprolyl', 'nsceramide', 'nucifera', 'nylon', 'nymphaea', 'oasis', 'oat', 'obovata', 'occurs', 'ocimum', 'octanediol', 'octenylsuccinate', 'octocrylene', 'octyl', 'octyldodecanol', 'ocymenol', 'oethyl', 'officinalis', 'officinarum', 'oil', 'oils', 'olea', 'oleanolic', 'oleate', 'oleic', 'oleifera', 'oleracea', 'oligopeptide', 'onsen', 'onsensui', 'opuntia', 'orange', 'oryza', 'ovinus', 'oxide', 'oxides', 'pallidum', 'palmitamide', 'palmitate', 'palmitic', 'palmitoyl', 'panax', 'panthenol', 'paola', 'papaya', 'paraffin', 'paraffinum', 'paraffium', 'pareth', 'parfum', 'parkii', 'parthenium', 'pca', 'pcresol', 'peel', 'peeling', 'peg', 'peghdi', 'pegppg', 'pentaerythrityl', 'pentanedione', 'pentylene', 'peppermint', 'peptide', 'peptinol', 'perfect', 'perforatum', 'perfume', 'persea', 'ph', 'phaseolus', 'phenethyl', 'phenoxyethanol', 'phenyl', 'phenylbenzimidazole', 'phenylpropanol', 'phosphate', 'phospholipids', 'phthalic', 'phytate', 'phyto', 'phytosphingosine', 'piperita', 'pistacia', 'plantensis', 'platensis', 'plum', 'plumeria', 'pmethoxycinnamate', 'polyacrylamide', 'polyacrylate', 'polyacryloyldimethyl', 'polyacyladipate', 'polydimethylsiloxyethyl', 'polyester', 'polyethylene', 'polyglutamic', 'polyglyceryl', 'polygonum', 'polyhydroxystearic', 'polylysine', 'polymethyl', 'polymethylmethacrylate', 'polymethylsilsesquioxane', 'polypropylsilsesquioxane', 'polyquartenum', 'polyquaternium', 'polysaccharide', 'polysilicone', 'polysorbate', 'polyvinyl', 'pom', 'pore', 'portulaca', 'potassium', 'potion', 'powder', 'power', 'ppgbuteth', 'pratense', 'pretty', 'proline', 'propanediol', 'propanol', 'propolis', 'propylene', 'propylheptyl', 'propylparaben', 'protein', 'proteinpvp', 'prunus', 'psidium', 'punica', 'purifying', 'purpurea', 'pvp', 'pyridoxine', 'pyrifera', 'pyrus', 'quartz', 'quaternium', 'quillaja', 'radiant', 'radiatus', 'raffinose', 'raspberry', 'ready', 'recutita', 'rena', 'resistant', 'resveratrol', 'retinoate', 'retinoid', 'retinol', 'retinyl', 'rhamnoides', 'rice', 'rich', 'root', 'rosa', 'rose', 'rosemary', 'rosmarinus', 'royal', 'rubus', 'sabun', 'saccharide', 'saccharomyces', 'saccharum', 'sage', 'salicylate', 'salicylic', 'salix', 'salvia', 'sanctum', 'saponaria', 'saposhnikovia', 'sappan', 'sarcosine', 'sargassum', 'sativa', 'sativus', 'saviour', 'schizophyllan', 'sea', 'sebum', 'seed', 'sekken', 'senegal', 'series', 'serine', 'serrata', 'serum', 'shea', 'shield', 'sholigopeptide', 'shpolypeptide', 'silane', 'silica', 'silk', 'silsesquioxane', 'silylate', 'simmondsia', 'simply', 'sinensis', 'size', 'skin', 'skinpair', 'smooth', 'sodium', 'soil', 'soja', 'sojik', 'solanum', 'solution', 'soothing', 'sophora', 'sorbate', 'sorbitan', 'sorbitol', 'spf', 'spfpa', 'sphingolipids', 'spinosa', 'spirulina', 'spot', 'sprout', 'squalane', 'squalene', 'starch', 'stay', 'stearate', 'stearatecetyl', 'steareth', 'stearic', 'stearoyl', 'stearyl', 'stem', 'stick', 'strawberry', 'styrene', 'styreneacrylates', 'succinic', 'sucrose', 'sugarcane', 'sulfate', 'sulfonic', 'sulfosuccinate', 'sunday', 'sunessence', 'sunflower', 'sunscreen', 'supple', 'supreme', 'surfactin', 'surge', 'synthetic', 'syringylidenemalonate', 'talc', 'tamarindus', 'tamariscifolia', 'tangerina', 'tangerine', 'taurate', 'tbutyl', 'tea', 'tephrosia', 'terephthalylidene', 'terminalia', 'tertrasodium', 'tetrahexyldecyl', 'tetraisopalmitate', 'tetraisostearate', 'tetramethylbutylphenol', 'tetramethylhydroxypiperidinol', 'tetrapeptide', 'tetrasodium', 'threonine', 'tightening', 'titanium', 'tocopherol', 'tocopheryl', 'tone', 'toned', 'toner', 'totarol', 'tranexamic', 'translucent', 'treatment', 'tree', 'trehalose', 'tremella', 'triazine', 'triazone', 'triethanol', 'triethanolamine', 'triethoxycaprylylsilane', 'triethylene', 'triethylhexanoin', 'trifolium', 'triglyceride', 'triisostearate', 'trikenol', 'trimethicone', 'trimethoxybenzylidene', 'tripeptide', 'triple', 'tris', 'trisodium', 'tromethamine', 'turmeric', 'ubiquinone', 'unshiu', 'uralensis', 'urea', 'uv', 'uva', 'uvb', 'vaccinium', 'vegetable', 'vera', 'vinifera', 'vinyl', 'virginia', 'virginiana', 'viscum', 'vit', 'vitamin', 'vitis', 'volcanic', 'vulgar', 'vulgare', 'wajah', 'wash', 'water', 'waterizer', 'watery', 'wax', 'weight', 'wheat', 'willow', 'witch', 'wowtery', 'xanthan', 'xylitol', 'xylitylglucoside', 'yellow', 'ysb', 'zea', 'zeylanicum', 'zinc']

In [32]:
n_data = len(dataset)
n_kata = len(word_vocab)

data_tf = pd.DataFrame(np.zeros((n_data, n_kata)), columns=list(word_vocab))
 
# Compute Term Frequency (TF)
for i in range(n_data):
    words = dataset['data'][i].split() # Words in the document
    for w in words:
        data_tf[w][i] = data_tf[w][i] + (1 / len(words))
         
data_tf

,acacia,acer,acetate,acetyl,acetylated,achillea,acid,acids,acne,acneact,...,witch,wowtery,xanthan,xylitol,xylitylglucoside,yellow,ysb,zea,zeylanicum,zinc
0,0.0,0.0,0.011364,0.011364,0.000000,0.0,0.068182,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.022989,0.0,0.011494,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.000000,0.010204,0.0,0.040816,0.0,0.000000,0.0,...,0.0,0.010204,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.000000,0.010417,0.0,0.052083,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.000000,0.010753,0.0,0.064516,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.062500,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.018182,0.000000,0.018182,0.0,0.054545,0.0,0.000000,0.0,...,0.0,0.000000,0.018182,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.022222,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.027027,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## PERHITUNGAN TF MANUAL

In [33]:
n_data = len(dataset['data'])
n_kata = len(word_vocab)

data_tf = pd.DataFrame(np.zeros((n_data, n_kata)), columns=list(word_vocab))
 
# Compute Term Frequency (TF)
temp = 0
a=[]
for i in range(n_data):
    
    words = dataset['data'][i].split() # Words in the document
    for w in words:
        data_tf[w][i] = data_tf[w][i] + 1 / len(words) 
    
    
data_tf

,acacia,acer,acetate,acetyl,acetylated,achillea,acid,acids,acne,acneact,...,witch,wowtery,xanthan,xylitol,xylitylglucoside,yellow,ysb,zea,zeylanicum,zinc
0,0.0,0.0,0.011364,0.011364,0.000000,0.0,0.068182,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.022989,0.0,0.011494,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.000000,0.010204,0.0,0.040816,0.0,0.000000,0.0,...,0.0,0.010204,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.000000,0.010417,0.0,0.052083,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.000000,0.010753,0.0,0.064516,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.062500,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.018182,0.000000,0.018182,0.0,0.054545,0.0,0.000000,0.0,...,0.0,0.000000,0.018182,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.022222,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.027027,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
#Menjadikan dataset file xlsx
data_tf.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/NEW/" +'hasilTF.xlsx', index=False)

## PERHITUNGAN IDF MANUAL

In [35]:
idf = {}
 
for w in word_vocab:
    n = 0   
     
    for i in range(n_data):
        if w in dataset['data'][i].split():
            n += 1
             
    idf[w] =  (np.log((1+n_data)/(1+n)))+1
     
    # print(f'{w:>15}: {idf[w]:>10}' )

print(idf)

{'acacia': 4.921973336281314, 'acer': 4.921973336281314, 'acetate': 2.670681537674819, 'acetyl': 3.8233610476132043, 'acetylated': 3.130213867053259, 'achillea': 4.921973336281314, 'acid': 1.2843871765549284, 'acids': 4.921973336281314, 'acne': 3.5356789751614235, 'acneact': 4.921973336281314, 'acnedot': 4.921973336281314, 'acneplus': 4.51650822817315, 'acocia': 4.921973336281314, 'acrylate': 3.217225244042889, 'acrylateacrylic': 3.8233610476132043, 'acrylates': 2.907070315739049, 'acrylatesc': 3.312535423847214, 'acrylatesodium': 3.130213867053259, 'acrylatespolytrimethylsiloxymethacrylate': 4.921973336281314, 'acryloyldimethyl': 3.130213867053259, 'acryloyldimethyltauratecarboxyethyl': 4.921973336281314, 'acryloyldimethyltauratevp': 4.51650822817315, 'actinidia': 4.51650822817315, 'acttackantiacne': 4.921973336281314, 'adansonia': 4.921973336281314, 'adenosine': 4.005682604407159, 'adipate': 4.005682604407159, 'age': 4.921973336281314, 'agent': 4.51650822817315, 'ahabhapha': 4.921973336281314, 'alba': 3.41789593950504, 'albatrellus': 4.228826155721369, 'albizia': 4.921973336281314, 'album': 4.51650822817315, 'alcohol': 2.357023978819777, 'alcohols': 4.921973336281314, 'algae': 4.921973336281314, 'algin': 4.921973336281314, 'alginate': 4.921973336281314, 'alkane': 4.228826155721369, 'alkyl': 3.130213867053259, 'allantoin': 1.8309308829229982, 'aloe': 2.357023978819777, 'aloevera': 4.921973336281314, 'alpha': 4.921973336281314, 'alphaarbutin': 4.51650822817315, 'alpinum': 4.921973336281314, 'alternafolia': 4.921973336281314, 'alternifolia': 4.005682604407159, 'alumina': 4.51650822817315, 'aluminum': 4.005682604407159, 'amber': 4.921973336281314, 'amide': 4.005682604407159, 'amine': 4.921973336281314, 'amino': 3.8233610476132043, 'aminobutanol': 4.921973336281314, 'aminobutyric': 4.921973336281314, 'aminomethyl': 4.921973336281314, 'ammonium': 3.5356789751614235, 'amurense': 4.921973336281314, 'angelica': 4.921973336281314, 'angustifolia': 4.921973336281314, 'angustifolium': 4.51650822817315, 'anhydroxylitol': 3.8233610476132043, 'annona': 4.921973336281314, 'annuus': 4.921973336281314, 'anthemis': 4.228826155721369, 'antioxidant': 4.921973336281314, 'apple': 4.921973336281314, 'aqua': 1.6077873316087885, 'aquabloom': 4.921973336281314, 'arachidyl': 4.921973336281314, 'arachis': 4.921973336281314, 'arbutin': 3.8233610476132043, 'arctium': 4.921973336281314, 'argania': 4.921973336281314, 'arginine': 4.51650822817315, 'arisaema': 4.921973336281314, 'artemisia': 3.8233610476132043, 'arvensis': 4.51650822817315, 'ascorbate': 4.228826155721369, 'ascorbic': 3.41789593950504, 'ascorbyl': 3.6692103677859462, 'asiatic': 4.921973336281314, 'asiatica': 2.357023978819777, 'asiaticoside': 4.51650822817315, 'aspartate': 4.51650822817315, 'aspartic': 3.8233610476132043, 'astragalus': 4.51650822817315, 'aura': 4.921973336281314, 'aurantium': 4.005682604407159, 'avena': 4.005682604407159, 'aviculare': 4.921973336281314, 'avocado': 4.921973336281314, 'azadirachta': 4.51650822817315, 'bacillusfolic': 4.921973336281314, 'bacillussoybeanfolic': 4.921973336281314, 'backhouisa': 4.51650822817315, 'bae': 4.005682604407159, 'bakuchiol': 4.228826155721369, 'balancing': 4.921973336281314, 'balm': 4.921973336281314, 'bank': 4.921973336281314, 'barbadensis': 2.47962630091211, 'bark': 3.6692103677859462, 'barrier': 4.228826155721369, 'bb': 4.921973336281314, 'beat': 4.921973336281314, 'beeswax': 4.921973336281314, 'beet': 4.921973336281314, 'behenate': 4.921973336281314, 'behenyl': 4.228826155721369, 'beneath': 4.228826155721369, 'benzoate': 2.2829160066660554, 'benzoic': 4.51650822817315, 'benzotriazolyl': 4.51650822817315, 'benzyl': 4.51650822817315, 'bergamia': 4.51650822817315, 'bergamot': 4.51650822817315, 'berry': 4.921973336281314, 'beta': 4.228826155721369, 'betaglucan': 4.51650822817315, 'betaine': 2.670681537674819, 'bha': 4.51650822817315, 'bht': 3.5356789751614235, 'bicarbonate': 4.921973336281314, 'bifida': 4.51650822817315, 'biome': 4.921973336281314, 'biosaccharide': 4.228826155721369, 'biotin': 4.228826155721369, 'bisabolol': 3.5356789751614235, 'bisbenzotriazolyl': 4.228826155721369, 'bisdecyltetradeceth': 4.921973336281314, 'bisdiglyceryl': 4.921973336281314, 'bisethylhexyloxyphenol': 3.6692103677859462, 'bisglyceryl': 4.921973336281314, 'bispeg': 4.921973336281314, 'bisulfite': 4.921973336281314, 'block': 4.921973336281314, 'blue': 4.921973336281314, 'blueberry': 4.921973336281314, 'blur': 4.921973336281314, 'bodyguard': 4.921973336281314, 'bomb': 4.921973336281314, 'booster': 4.51650822817315, 'boswellia': 4.921973336281314, 'botanical': 4.228826155721369, 'bounce': 4.51650822817315, 'bran': 4.228826155721369, 'brassica': 4.921973336281314, 'bright': 4.921973336281314, 'brightening': 4.228826155721369, 'brighter': 4.921973336281314, 'brigth': 4.921973336281314, 'bring': 4.921973336281314, 'broccoli': 4.921973336281314, 'buckthorn': 4.921973336281314, 'buster': 4.921973336281314, 'butter': 4.228826155721369, 'butyl': 3.312535423847214, 'butylene': 1.6077873316087885, 'butyloctyl': 4.228826155721369, 'butyrospermum': 4.228826155721369, 'caesalpinia': 4.51650822817315, 'caffeine': 4.228826155721369, 'calcium': 4.51650822817315, 'calendula': 3.8233610476132043, 'calm': 4.921973336281314, 'calming': 4.921973336281314, 'camellia': 3.130213867053259, 'camphor': 4.51650822817315, 'canina': 4.228826155721369, 'capillaris': 4.51650822817315, 'caprate': 4.228826155721369, 'capric': 4.921973336281314, 'caprylate': 3.5356789751614235, 'caprylhydroxamic': 4.51650822817315, 'caprylic': 4.921973336281314, 'capryliccapric': 2.47962630091211, 'capryloyl': 4.51650822817315, 'caprylyl': 2.670681537674819, 'caprylylcapryl': 4.921973336281314, 'carbamate': 4.921973336281314, 'carbanate': 4.921973336281314, 'carbomer': 2.7819071727850435, 'carbonate': 3.6692103677859462, 'care': 4.51650822817315, 'carica': 4.228826155721369, 'carrot': 4.921973336281314, 'castor': 2.7247487589450947, 'cell': 4.51650822817315, 'cellulose': 4.228826155721369, 'centelaasiatica': 4.921973336281314, 'centella': 2.357023978819777, 'cera': 4.921973336281314, 'ceramic': 4.921973336281314, 'ceramide': 2.5240780634829436, 'ceresin': 4.921973336281314, 'ceteareth': 4.921973336281314, 'cetearyl': 3.5356789751614235, 'ceteraryl': 4.921973336281314, 'ceteth': 4.228826155721369, 'cetyl': 3.0501711593797225, 'chamomile': 4.921973336281314, 'chamomilla': 4.005682604407159, 'chebula': 4.921973336281314, 'chemical': 4.921973336281314, 'cherimola': 4.921973336281314, 'chiloensis': 4.51650822817315, 'chinensis': 4.228826155721369, 'chlorantha': 4.921973336281314, 'chlorella': 4.921973336281314, 'chlorhexidine': 4.921973336281314, 'chloride': 2.907070315739049, 'chlorphenesin': 2.0597724553518457, 'cholesterol': 3.312535423847214, 'choleth': 4.921973336281314, 'chondrus': 4.921973336281314, 'chromanyl': 4.921973336281314, 'chrysanthemum': 4.51650822817315, 'chrysin': 4.921973336281314, 'cica': 4.228826155721369, 'cinnamomum': 4.228826155721369, 'citrate': 3.41789593950504, 'citric': 2.1811333123561134, 'citriodora': 4.51650822817315, 'citrus': 3.130213867053259, 'cleanser': 3.41789593950504, 'cleansing': 4.51650822817315, 'cloud': 4.51650822817315, 'clover': 4.921973336281314, 'cocamide': 4.005682604407159, 'cocamidopropyl': 2.976063187226001, 'coccinia': 4.51650822817315, 'cocoamphodiacetate': 4.921973336281314, 'cocoate': 3.8233610476132043, 'cocobetaine': 4.51650822817315, 'cococaprylatecaprate': 4.921973336281314, 'cocoglucoside': 4.921973336281314, 'coconut': 4.005682604407159, 'cocos': 4.51650822817315, 'cocoy': 4.921973336281314, 'cocoyl': 3.6692103677859462, 'collagen': 4.005682604407159, 'colloidal': 4.51650822817315, 'comb': 4.921973336281314, 'communis': 4.921973336281314, 'complete': 4.921973336281314, 'complex': 4.51650822817315, 'concentrate': 4.921973336281314, 'confluens': 4.51650822817315, 'control': 4.228826155721369, 'copolymer': 2.3192836508369306, 'copper': 3.6692103677859462, 'corallina': 4.51650822817315, 'cordyceps': 4.921973336281314, 'corn': 4.005682604407159, 'corymbosum': 4.921973336281314, 'cr': 4.921973336281314, 'cream': 4.51650822817315, 'creamy': 4.921973336281314, 'creatine': 4.921973336281314, 'creme': 4.921973336281314, 'crispus': 4.921973336281314, 'crosspolymer': 2.2139231351791038, 'crystallinum': 3.8233610476132043, 'cucumber': 4.228826155721369, 'cucumis': 3.8233610476132043, 'culture': 4.921973336281314, 'curcuma': 4.228826155721369, 'cyanocobalamin': 4.51650822817315, 'cyclohexasiloxane': 4.921973336281314, 'cyclomethicone': 4.921973336281314, 'cyclopentasiloxane': 3.5356789751614235, 'cyclotetrasiloxane': 4.921973336281314, 'cystoseira': 4.921973336281314, 'daily': 3.8233610476132043, 'damascena': 4.921973336281314, 'dear': 4.921973336281314, 'decy': 4.921973336281314, 'decyl': 3.312535423847214, 'decylene': 4.51650822817315, 'deep': 4.51650822817315, 'deepcleanse': 4.921973336281314, 'defender': 4.921973336281314, 'defense': 4.921973336281314, 'dehydroacetate': 4.921973336281314, 'dehydroacetic': 4.51650822817315, 'delima': 4.921973336281314, 'deoxyphytantriyl': 4.228826155721369, 'dew': 4.51650822817315, 'diamond': 4.921973336281314, 'dibutyl': 4.005682604407159, 'dicamphor': 4.921973336281314, 'dicaprylatedicaprate': 4.51650822817315, 'dicaprylyl': 3.8233610476132043, 'dicetyl': 4.921973336281314, 'diethylamino': 3.8233610476132043, 'diethylhexyl': 4.921973336281314, 'digitata': 4.921973336281314, 'digluconate': 4.921973336281314, 'diglycerin': 4.921973336281314, 'diglycidyl': 4.921973336281314, 'diheptanoate': 4.51650822817315, 'dihydroxypropy': 4.921973336281314, 'dihydroxypropyl': 4.921973336281314, 'diisethionate': 4.921973336281314, 'diisostearate': 4.921973336281314, 'dimethicone': 2.7819071727850435, 'dimethiconemethicone': 4.228826155721369, 'dimethiconepeg': 4.921973336281314, 'dimethiconevinyl': 4.51650822817315, 'dimethiconol': 4.921973336281314, 'dimethyl': 4.228826155721369, 'dimethylmethoxy': 4.921973336281314, 'dimethylsilanol': 4.921973336281314, 'dioleate': 4.005682604407159, 'dioxide': 3.5356789751614235, 'dipentaerythrityl': 4.921973336281314, 'dipeptide': 4.921973336281314, 'diphenylsiloxy': 4.921973336281314, 'dipotassium': 3.41789593950504, 'dipropylene': 3.6692103677859462, 'distearate': 3.217225244042889, 'distearyl': 4.005682604407159, 'disuccinate': 4.921973336281314, 'divaricata': 4.921973336281314, 'divine': 4.921973336281314, 'dmdm': 4.005682604407159, 'dodecyl': 4.51650822817315, 'domestica': 4.921973336281314, 'dont': 4.921973336281314, 'dor': 4.921973336281314, 'dpanthenol': 4.51650822817315, 'dream': 4.921973336281314, 'dry': 4.921973336281314, 'dulcis': 4.005682604407159, 'ectoin': 4.228826155721369, 'edta': 1.6448286032891377, 'eggplant': 4.51650822817315, 'ekstrak': 4.921973336281314, 'elata': 4.921973336281314, 'elixir': 4.921973336281314, 'enantia': 4.921973336281314, 'eop': 4.228826155721369, 'epilobium': 4.51650822817315, 'essence': 3.6692103677859462, 'essencetoner': 4.921973336281314, 'essential': 4.921973336281314, 'ester': 4.921973336281314, 'esters': 4.51650822817315, 'ether': 4.921973336281314, 'ethersodium': 4.921973336281314, 'ethoxydiglycol': 4.51650822817315, 'ethyl': 4.51650822817315, 'ethylenediamine': 4.921973336281314, 'ethylhexanoate': 4.51650822817315, 'ethylhexyglycerin': 4.921973336281314, 'ethylhexyl': 2.7247487589450947, 'ethylhexylglycerin': 1.9775343571148736, 'europaea': 4.51650822817315, 'exctract': 4.921973336281314, 'expressed': 4.921973336281314, 'extract': 1.1962799090446616, 'extracts': 4.921973336281314, 'face': 1.853920401147697, 'facial': 2.47962630091211, 'fagopyrum': 4.921973336281314, 'fennel': 4.921973336281314, 'ferdinandiana': 4.921973336281314, 'ferment': 2.842531794601478, 'ferulic': 4.921973336281314, 'feverfew': 4.51650822817315, 'ficus': 4.921973336281314, 'ficusindica': 4.921973336281314, 'fig': 4.921973336281314, 'filter': 4.51650822817315, 'filtrate': 3.5356789751614235, 'flavour': 4.51650822817315, 'florida': 4.921973336281314, 'flour': 4.921973336281314, 'flower': 2.6193882432872684, 'flowerleaf': 4.921973336281314, 'flowerleafstem': 4.51650822817315, 'foam': 4.005682604407159, 'foeniculum': 4.921973336281314, 'folic': 4.921973336281314, 'fomes': 4.921973336281314, 'forget': 4.921973336281314, 'fqp': 4.921973336281314, 'fragaria': 4.51650822817315, 'fragrance': 4.005682604407159, 'frangipani': 4.921973336281314, 'free': 4.921973336281314, 'fresh': 4.921973336281314, 'fructooligosaccharides': 4.51650822817315, 'fructose': 4.921973336281314, 'fruit': 2.0597724553518457, 'fruitleaf': 4.921973336281314, 'fuciformis': 4.228826155721369, 'full': 4.921973336281314, 'galactomyces': 4.005682604407159, 'galactosyl': 4.921973336281314, 'ganoderma': 4.921973336281314, 'garcinia': 4.51650822817315, 'gardenia': 4.921973336281314, 'gastrodia': 4.921973336281314, 'gel': 3.217225244042889, 'gellan': 4.921973336281314, 'gentle': 4.921973336281314, 'germ': 4.921973336281314, 'gigas': 4.921973336281314, 'ginseng': 4.921973336281314, 'glabra': 4.005682604407159, 'glow': 4.921973336281314, 'glowin': 4.921973336281314, 'glowing': 4.228826155721369, 'glucan': 4.921973336281314, 'gluconate': 4.228826155721369, 'gluconobacterhoney': 4.51650822817315, 'gluconolactone': 4.921973336281314, 'glucose': 3.41789593950504, 'glucoside': 2.7819071727850435, 'glutamate': 4.005682604407159, 'glutamine': 4.921973336281314, 'glycereth': 4.921973336281314, 'glycerin': 1.2330938821673778, 'glyceryl': 2.3962446919730587, 'glycerylnstearate': 4.921973336281314, 'glycinate': 4.005682604407159, 'glycine': 4.005682604407159, 'glycol': 1.3384543978252041, 'glycolic': 4.228826155721369, 'glycyrrhiza': 3.312535423847214, 'glycyrrhizate': 3.41789593950504, 'glyrcinate': 4.921973336281314, 'goals': 4.921973336281314, 'gold': 4.51650822817315, 'golden': 4.921973336281314, 'granactive': 4.921973336281314, 'granatum': 4.228826155721369, 'grape': 4.921973336281314, 'gratissima': 4.921973336281314, 'great': 4.921973336281314, 'green': 4.228826155721369, 'guaiazulene': 4.921973336281314, 'guajava': 4.921973336281314, 'guava': 4.921973336281314, 'gum': 2.004202604197035, 'hamamelis': 4.51650822817315, 'hazel': 4.51650822817315, 'hc': 4.921973336281314, 'hcl': 4.005682604407159, 'hditrimethylol': 4.921973336281314, 'helianthus': 4.921973336281314, 'helios': 4.921973336281314, 'herb': 4.921973336281314, 'hexa': 4.921973336281314, 'hexamidine': 4.921973336281314, 'hexanediol': 2.0597724553518457, 'hexapeptide': 3.8233610476132043, 'hexyl': 3.6692103677859462, 'hexylene': 4.51650822817315, 'hexyllactone': 4.921973336281314, 'hexylresorcinol': 4.921973336281314, 'hippophae': 4.51650822817315, 'histidine': 4.005682604407159, 'holyshield': 4.921973336281314, 'honey': 4.005682604407159, 'hops': 4.921973336281314, 'hour': 4.921973336281314, 'humulus': 4.921973336281314, 'hyacross': 4.921973336281314, 'hyaluronate': 1.951558870711613, 'hyaluronatecrosspolymer': 4.921973336281314, 'hyaluronic': 2.842531794601478, 'hybrid': 4.921973336281314, 'hydantoin': 4.005682604407159, 'hydra': 4.921973336281314, 'hydralife': 4.921973336281314, 'hydramax': 4.921973336281314, 'hydramaxc': 4.921973336281314, 'hydrasoothe': 4.921973336281314, 'hydrated': 4.921973336281314, 'hydrating': 3.8233610476132043, 'hydro': 4.921973336281314, 'hydrogenated': 2.1811333123561134, 'hydrolized': 4.921973336281314, 'hydrolyzed': 2.570598079117836, 'hydroxide': 2.976063187226001, 'hydroxyacetophenone': 3.312535423847214, 'hydroxybenzoyl': 3.8233610476132043, 'hydroxydecenoic': 4.921973336281314, 'hydroxyethyl': 3.312535423847214, 'hydroxyethylcellulose': 4.228826155721369, 'hydroxymethylglycinate': 4.51650822817315, 'hydroxypinacolone': 4.921973336281314, 'hydroxypropyl': 4.228826155721369, 'hydroxypropyltrimonium': 3.5356789751614235, 'hydroxysultaine': 4.51650822817315, 'hypericum': 4.921973336281314, 'hypogaea': 4.921973336281314, 'idaeus': 4.005682604407159, 'illite': 4.921973336281314, 'indica': 4.228826155721369, 'ingredients': 4.921973336281314, 'ingredientsceramide': 4.921973336281314, 'intense': 4.921973336281314, 'inulin': 4.51650822817315, 'iron': 4.51650822817315, 'isethionate': 4.921973336281314, 'isinonyl': 4.921973336281314, 'isoamyl': 4.51650822817315, 'isododecane': 4.51650822817315, 'isohexadecane': 3.41789593950504, 'isomerate': 4.228826155721369, 'isononanoate': 4.51650822817315, 'isoparaffin': 3.5356789751614235, 'isopropyl': 4.228826155721369, 'isosorbide': 4.921973336281314, 'isostearate': 4.005682604407159, 'isotridecyl': 4.921973336281314, 'italica': 4.921973336281314, 'japonica': 4.51650822817315, 'jelly': 3.8233610476132043, 'jerawat': 2.088759992225098, 'jojoba': 4.51650822817315, 'juice': 3.217225244042889, 'julibrissin': 4.921973336281314, 'juniperus': 4.921973336281314, 'junos': 4.228826155721369, 'kakadu': 4.921973336281314, 'kale': 4.921973336281314, 'kaolin': 4.921973336281314, 'kering': 1.1962799090446616, 'kernel': 4.005682604407159, 'key': 4.921973336281314, 'kind': 4.921973336281314, 'kombinasi': 1.2843871765549284, 'kusam': 1.6638767982598321, 'kusamjerawat': 4.921973336281314, 'lactate': 4.51650822817315, 'lactic': 3.130213867053259, 'lactobacillus': 4.51650822817315, 'lactobacilluscollagenmesembryanthemum': 4.005682604407159, 'lactobionic': 4.921973336281314, 'lactococcus': 4.51650822817315, 'lactose': 4.921973336281314, 'lactylate': 4.005682604407159, 'lannesiana': 4.921973336281314, 'laurate': 4.005682604407159, 'laureth': 2.6193882432872684, 'lauric': 4.921973336281314, 'laurocapram': 4.921973336281314, 'lauroyl': 4.005682604407159, 'lauryl': 3.0501711593797225, 'lavandula': 4.921973336281314, 'leaf': 1.7864791203521646, 'lecithin': 2.5240780634829436, 'lemon': 3.6692103677859462, 'lentiscus': 4.921973336281314, 'leontopodium': 4.921973336281314, 'licorice': 3.5356789751614235, 'light': 3.6692103677859462, 'limon': 4.228826155721369, 'limonene': 4.51650822817315, 'limonum': 4.228826155721369, 'linalool': 4.921973336281314, 'linoleic': 4.51650822817315, 'linolenic': 4.51650822817315, 'lipids': 4.921973336281314, 'liquidum': 4.51650822817315, 'long': 4.921973336281314, 'longa': 4.228826155721369, 'loose': 4.921973336281314, 'lotus': 4.921973336281314, 'lucidum': 4.921973336281314, 'luminous': 4.921973336281314, 'lupulus': 4.921973336281314, 'lysate': 3.41789593950504, 'macadamiate': 4.921973336281314, 'macrocystis': 4.921973336281314, 'madecassic': 4.921973336281314, 'madecassoside': 4.51650822817315, 'magnesium': 4.228826155721369, 'magnolia': 4.921973336281314, 'majus': 4.921973336281314, 'makeup': 4.921973336281314, 'malachite': 4.921973336281314, 'maltodextrin': 4.51650822817315, 'malus': 4.51650822817315, 'mandelic': 4.228826155721369, 'mangostana': 4.51650822817315, 'mannitol': 4.51650822817315, 'marigold': 4.51650822817315, 'marine': 4.921973336281314, 'mask': 4.921973336281314, 'mastic': 4.921973336281314, 'matcha': 4.921973336281314, 'matricaria': 4.005682604407159, 'mays': 4.228826155721369, 'me': 4.921973336281314, 'mea': 3.5356789751614235, 'meal': 4.921973336281314, 'medica': 4.228826155721369, 'melaleuca': 3.8233610476132043, 'melanin': 4.921973336281314, 'melia': 4.51650822817315, 'melissa': 4.51650822817315, 'melongena': 4.51650822817315, 'membranaceus': 4.51650822817315, 'memory': 4.921973336281314, 'mentha': 4.005682604407159, 'menthol': 4.228826155721369, 'mesembryanthemum': 4.921973336281314, 'methacrylate': 3.8233610476132043, 'methicone': 4.228826155721369, 'methoxycinnamate': 3.130213867053259, 'methoxydibenzoylmethane': 3.312535423847214, 'methoxyphenyl': 3.6692103677859462, 'methoxysalicylate': 4.921973336281314, 'methyl': 3.312535423847214, 'methylbenzylidene': 4.51650822817315, 'methylcellulose': 4.228826155721369, 'methylchloroisothiazolinone': 4.921973336281314, 'methylene': 4.228826155721369, 'methylglucose': 4.005682604407159, 'methylisothiazolinone': 4.921973336281314, 'methylparaben': 4.51650822817315, 'mica': 4.51650822817315, 'microcrystalline': 4.005682604407159, 'mild': 3.823

In [36]:
data_idf = pd.DataFrame.from_dict(idf, orient='index',columns=['Nilai IDF'])

In [37]:
data_idf

            Nilai IDF
acacia       4.921973
acer         4.921973
acetate      2.670682
acetyl       3.823361
acetylated   3.130214
...               ...
yellow       4.921973
ysb          4.921973
zea          4.228826
zeylanicum   4.228826
zinc         3.312535

[1016 rows x 1 columns]

In [38]:
#Menjadikan dataset file xlsx
data_idf.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/NEW/" +'hasilIDF.xlsx', index=False)

## TFIDF MANUAL

In [39]:
data_tf_idf = data_tf.copy()
 
for w in word_vocab:
    for i in range(n_data):
        data_tf_idf[w][i] = data_tf[w][i] * idf[w]
         
data_tf_idf

,acacia,acer,acetate,acetyl,acetylated,achillea,acid,acids,acne,acneact,...,witch,wowtery,xanthan,xylitol,xylitylglucoside,yellow,ysb,zea,zeylanicum,zinc
0,0.0,0.0,0.030349,0.043447,0.000000,0.0,0.087572,0.0,0.00000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.029526,0.0,0.04064,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.000000,0.031941,0.0,0.052424,0.0,0.00000,0.0,...,0.0,0.050224,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.000000,0.032606,0.0,0.066895,0.0,0.00000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.000000,0.033658,0.0,0.082864,0.0,0.00000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.00000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.080274,0.0,0.00000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.048558,0.000000,0.056913,0.0,0.070057,0.0,0.00000,0.0,...,0.0,0.000000,0.037977,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.00000,0.0,...,0.0,0.000000,0.046417,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.034713,0.0,0.00000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [40]:
#Melakukan normalisasi
from sklearn import preprocessing
import numpy as np

normalizd_arr = preprocessing.normalize(data_tf_idf)

after_normz = pd.DataFrame(normalizd_arr, columns=list(word_vocab) )
after_normz

,acacia,acer,acetate,acetyl,acetylated,achillea,acid,acids,acne,acneact,...,witch,wowtery,xanthan,xylitol,xylitylglucoside,yellow,ysb,zea,zeylanicum,zinc
0,0.0,0.0,0.080476,0.115209,0.000000,0.0,0.232215,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.078927,0.0,0.108635,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.000000,0.097488,0.0,0.160005,0.0,0.000000,0.0,...,0.0,0.153291,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.000000,0.101018,0.0,0.207249,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.000000,0.095813,0.0,0.235883,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.103857,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.113273,0.000000,0.132763,0.0,0.163426,0.0,0.000000,0.0,...,0.0,0.000000,0.088592,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.109768,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.053682,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# NEW

In [20]:
corpus = ['facial wash normal jerawat allantoin glycerin salicylic acid', 'kind facial wash facial wash normal minyak kering kombinasi normal kusam jerawat aqua cocamidopropyl betaine propylene glycol trehalose',
          'deep water face light makeup gel cleanser facial wash normal minyak kering kombinasi normal glycerin green tea']

In [21]:
the_wrd = []
for i in range(0, len(corpus)):
  words = corpus[i].split()
  for w in words :
    if w not in the_wrd:
      the_wrd.append(w)

the_wrd = sorted(the_wrd)
print(the_wrd)

['acid', 'allantoin', 'aqua', 'betaine', 'cleanser', 'cocamidopropyl', 'deep', 'face', 'facial', 'gel', 'glycerin', 'glycol', 'green', 'jerawat', 'kering', 'kind', 'kombinasi', 'kusam', 'light', 'makeup', 'minyak', 'normal', 'propylene', 'salicylic', 'tea', 'trehalose', 'wash', 'water']

In [22]:
import pandas as pd
import numpy as np


n_data = len(corpus)
n_kata = len(the_wrd)

data_tf = pd.DataFrame(np.zeros((n_data, n_kata)), columns=list(the_wrd))

# Compute Term Frequency (TF)
temp = 0
a = []
for i in range(n_data):

    words = corpus[i].split()  # Words in the document
    print(words)
    for w in words:
        data_tf[w][i] = data_tf[w][i] + 1 / len(words)


data_tf

['facial', 'wash', 'normal', 'jerawat', 'allantoin', 'glycerin', 'salicylic', 'acid']
['kind', 'facial', 'wash', 'facial', 'wash', 'normal', 'minyak', 'kering', 'kombinasi', 'normal', 'kusam', 'jerawat', 'aqua', 'cocamidopropyl', 'betaine', 'propylene', 'glycol', 'trehalose']
['deep', 'water', 'face', 'light', 'makeup', 'gel', 'cleanser', 'facial', 'wash', 'normal', 'minyak', 'kering', 'kombinasi', 'normal', 'glycerin', 'green', 'tea']

,acid,allantoin,aqua,betaine,cleanser,cocamidopropyl,deep,face,facial,gel,...,light,makeup,minyak,normal,propylene,salicylic,tea,trehalose,wash,water
0,0.125,0.125,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.125000,0.000000,...,0.000000,0.000000,0.000000,0.125000,0.000000,0.125,0.000000,0.000000,0.125000,0.000000
1,0.000,0.000,0.055556,0.055556,0.000000,0.055556,0.000000,0.000000,0.111111,0.000000,...,0.000000,0.000000,0.055556,0.111111,0.055556,0.000,0.000000,0.055556,0.111111,0.000000
2,0.000,0.000,0.000000,0.000000,0.058824,0.000000,0.058824,0.058824,0.058824,0.058824,...,0.058824,0.058824,0.058824,0.117647,0.000000,0.000,0.058824,0.000000,0.058824,0.058824

In [24]:
#Menjadikan dataset file xlsx
data_tf.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'TF_Manual_Laporan.xlsx', index=False)

In [34]:
idf = {}

for w in the_wrd:
    n = 0

    for i in range(n_data):
        if w in corpus[i].split():
            n += 1
    a = 1+n_data
    b = 1+n
    print(a,b)
    idf[w] =  (np.log((1+n_data)/(1+n)))+1

print(idf)
data_idf = pd.DataFrame.from_dict(idf, orient='index',columns=['Nilai IDF'])

data_idf.head(5)

4 2
4 2
4 2
4 2
4 2
4 2
4 2
4 2
4 4
4 2
4 3
4 2
4 2
4 3
4 3
4 2
4 3
4 2
4 2
4 2
4 3
4 4
4 2
4 2
4 2
4 2
4 4
4 2
{'acid': 1.6931471805599454, 'allantoin': 1.6931471805599454, 'aqua': 1.6931471805599454, 'betaine': 1.6931471805599454, 'cleanser': 1.6931471805599454, 'cocamidopropyl': 1.6931471805599454, 'deep': 1.6931471805599454, 'face': 1.6931471805599454, 'facial': 1.0, 'gel': 1.6931471805599454, 'glycerin': 1.2876820724517808, 'glycol': 1.6931471805599454, 'green': 1.6931471805599454, 'jerawat': 1.2876820724517808, 'kering': 1.2876820724517808, 'kind': 1.6931471805599454, 'kombinasi': 1.2876820724517808, 'kusam': 1.6931471805599454, 'light': 1.6931471805599454, 'makeup': 1.6931471805599454, 'minyak': 1.2876820724517808, 'normal': 1.0, 'propylene': 1.6931471805599454, 'salicylic': 1.6931471805599454, 'tea': 1.6931471805599454, 'trehalose': 1.6931471805599454, 'wash': 1.0, 'water': 1.6931471805599454}

           Nilai IDF
acid        1.693147
allantoin   1.693147
aqua        1.693147
betaine     1.693147
cleanser    1.693147

In [26]:
#Menjadikan dataset file xlsx
data_idf.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'IDF_Manual_Laporan.xlsx', index=False)

In [27]:
data_tf_idf = data_tf.copy()

for w in the_wrd:
    for i in range(n_data):
        data_tf_idf[w][i] = data_tf[w][i] * idf[w]

data_tf_idf

,acid,allantoin,aqua,betaine,cleanser,cocamidopropyl,deep,face,facial,gel,...,light,makeup,minyak,normal,propylene,salicylic,tea,trehalose,wash,water
0,0.211643,0.211643,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.125000,0.000000,...,0.000000,0.000000,0.000000,0.125000,0.000000,0.211643,0.000000,0.000000,0.125000,0.000000
1,0.000000,0.000000,0.094064,0.094064,0.000000,0.094064,0.000000,0.000000,0.111111,0.000000,...,0.000000,0.000000,0.071538,0.111111,0.094064,0.000000,0.000000,0.094064,0.111111,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.099597,0.000000,0.099597,0.099597,0.058824,0.099597,...,0.099597,0.099597,0.075746,0.117647,0.000000,0.000000,0.099597,0.000000,0.058824,0.099597

In [28]:
#Menjadikan dataset file xlsx
data_tf_idf.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'TF_IDF_Manual_Laporan.xlsx', index=False)

In [29]:
#Melakukan normalisasi
from sklearn import preprocessing
import numpy as np

normalizd_arr = preprocessing.normalize(data_tf_idf)

after_normz = pd.DataFrame(normalizd_arr, columns=list(the_wrd) )
after_normz

,acid,allantoin,aqua,betaine,cleanser,cocamidopropyl,deep,face,facial,gel,...,light,makeup,minyak,normal,propylene,salicylic,tea,trehalose,wash,water
0,0.438391,0.438391,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.258921,0.000000,...,0.000000,0.000000,0.000000,0.258921,0.000000,0.438391,0.000000,0.000000,0.258921,0.000000
1,0.000000,0.000000,0.262617,0.262617,0.000000,0.262617,0.000000,0.000000,0.310212,0.000000,...,0.000000,0.000000,0.199727,0.310212,0.262617,0.000000,0.000000,0.262617,0.310212,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.273112,0.000000,0.273112,0.273112,0.161305,0.273112,...,0.273112,0.273112,0.207709,0.322609,0.000000,0.000000,0.273112,0.000000,0.161305,0.273112

In [30]:
#Menjadikan dataset file xlsx
after_normz.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/" +'TF_IDF_Manual(AfterNormz)_Laporan.xlsx', index=False)

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(analyzer='word')
tfidf_dataset_coba = vectorizer.fit_transform(corpus)

df_tfidf_sklearn = pd.DataFrame(
    tfidf_dataset_coba.toarray(), columns=vectorizer.get_feature_names_out())
tfidf_tokens = vectorizer.get_feature_names_out()
df_tfidfvect = pd.DataFrame(data=tfidf_dataset_coba.toarray(
), index=[0,1,2], columns=tfidf_tokens)

df_tfidfvect

,acid,allantoin,aqua,betaine,cleanser,cocamidopropyl,deep,face,facial,gel,...,light,makeup,minyak,normal,propylene,salicylic,tea,trehalose,wash,water
0,0.438391,0.438391,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.258921,0.000000,...,0.000000,0.000000,0.000000,0.258921,0.000000,0.438391,0.000000,0.000000,0.258921,0.000000
1,0.000000,0.000000,0.262617,0.262617,0.000000,0.262617,0.000000,0.000000,0.310212,0.000000,...,0.000000,0.000000,0.199727,0.310212,0.262617,0.000000,0.000000,0.262617,0.310212,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.273112,0.000000,0.273112,0.273112,0.161305,0.273112,...,0.273112,0.273112,0.207709,0.322609,0.000000,0.000000,0.273112,0.000000,0.161305,0.273112

In [32]:
from sklearn.metrics.pairwise import cosine_similarity

cos_sim = cosine_similarity(data_tf_idf, data_tf_idf)
# print(cos_sim)
df_cosim = pd.DataFrame(data=cos_sim)
display(df_cosim)

          0         1         2
0  1.000000  0.307551  0.236312
1  0.307551  1.000000  0.324610
2  0.236312  0.324610  1.000000

In [33]:
from sklearn.metrics.pairwise import cosine_similarity

cos_sim = cosine_similarity(tfidf_dataset_coba, tfidf_dataset_coba)
# print(cos_sim)
df_cosim = pd.DataFrame(data=cos_sim)
display(df_cosim)

          0         1         2
0  1.000000  0.307551  0.236312
1  0.307551  1.000000  0.324610
2  0.236312  0.324610  1.000000

# TF-IDF DAN COSINE SIMILARITY

In [41]:
pip install -U scikit-learn

Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (1.24.2)
Requirement already satisfied: scipy>=1.3.2 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (from scikit-learn) (3.1.0)
Note: you may need to restart the kernel to use updated packages.

## Proses tahapan preprocessing terhadap inputan pengguna

In [42]:
#TEXT PREPROCESSING INPUTAN
def text_pre_input (user_input):
  # CASE FOLDING
    user_input = user_input.lower()

  # TOKENIZING
    # Menghapus Angka
    user_input = re.sub(r"\d+", "", user_input)
    # Menghapus Tanda Baca
    user_input = user_input.translate(
        str.maketrans("", "", string.punctuation))
    # Menghapus Simbol (@)
    user_input = re.sub(r"@\S+", "", user_input)
    # Menghapus URL
    user_input = re.sub("http[s]?\://\S+", "", user_input)
    # Menghapus tab atau line karakter
    user_input = re.sub(r"\n", "", user_input)
    # Menghapus berlebihan spasi
    user_input = re.sub('\s+', ' ', user_input)
    # dilakukan proses tokenization pada user_input
    tokens_query = [str(tok) for tok in nltk.word_tokenize(user_input)]

  # FILTERING
    # Stopword Bahasa Indonesia
    indo_stopword = set(stopwords.words('indonesian'))

    # Stopword Bahasa Inggris
    eng_stopword = set(stopwords.words('english'))

    # Data Stopword
    data_stopword = str(indo_stopword) + " " + str(eng_stopword)

    # Data tanpa stopword
    tokens_query = [word for word in tokens_query if not word in data_stopword]

  # STEMMING
    the_query = []
    # Membuat stemmer
    Factory = StemmerFactory()
    Stemmer = Factory.create_stemmer()
    for i in range(0, len(tokens_query)):
        tokens_query[i] = Stemmer.stem(tokens_query[i])
        the_query.append(tokens_query[i])

    join_query = ' '.join(tokens_query)
    return (tokens_query)

## Proses perhitungan cosine similarity untuk mendapatkan rekomendasi produk

In [43]:
#COSINE SIMILARITY AND GET THE RECOMMENDATION
from sklearn.metrics.pairwise import cosine_similarity

def get_recommendations_product(user_input, tfidf_dataset):

    # Melakukan perhitungan TFIDF terhadap inputan pengguna kepada keseluruhan data kata
    embed_query = vectorizer.transform(user_input)

    # Mencari tingkat kemiripan antara user_input dengan dataset
    cos_sim = cosine_similarity(embed_query, tfidf_dataset)

    # Mencari rata rata dari nilai kemiripan antara inputan pengguna dengan data produk
    cos_sim_a = np.mean(cos_sim, axis=0)
    
    # Membuat dataframe untuk hasil similaritas
    df_cosim = pd.DataFrame(data=cos_sim)
    # display(df_cosim)
    # Membuat dataframe hasil rata rata
    df_cosim_a = pd.DataFrame(data=cos_sim_a, columns=["cosine similarity score"])

    # Mencari 5 teratas nilai kemiripan tertinggi
    top5 = df_cosim_a.sort_values("cosine similarity score", ascending=False).head(5)
    # display(top5)

    # Mencari index dari 5 nilai kemiripan teratas
    index = list(top5.index.values)

    # Menyimpan nilai cosine similarity
    value_cosine = list(top5.values)

    return index, top5

## Proses penerimaan inputan, perhitungan tf idf data produk, dan penampilan hasil rekomendasi

In [44]:
#TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import Normalizer

# TFIDF
vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))
tfidf_dataset = vectorizer.fit_transform(dataset['data'])

# Melakukan test pada suatu kondisi
test_case = 'sunscreen kombinasi normal hyaluronic acid lactic acid retinol vitamin vitamin' 
user_input = text_pre_input(test_case)
index, top5 = get_recommendations_product(user_input, tfidf_dataset)

res_data = pd.DataFrame(data_product[['Nama', 'Jenis ']].iloc[index])
fix_res = res_data.join(top5)
# display(res_data)
# display(top5)
display(fix_res)

,Nama,Jenis,cosine similarity score
99,Perfect Shield Sunscreen Normal To Dry Skin Spf 30/Pa++,Sunscreen,0.122600
86,Block It Out Sunscreen,Sunscreen,0.108216
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.095945
97,Hydramax-C Sunscreen Serum,Sunscreen,0.092618
96,Tone Up UV Elixir SPF 50+ PA++++,Sunscreen,0.091262

In [45]:
# Mendapatkan fitur kata dari tfidf
df_tfidf_sklearn = pd.DataFrame(tfidf_dataset.toarray(),columns=vectorizer.get_feature_names_out())
df_tfidf_sklearn

# #Mendapatkan nama setiap kata
tfidf_tokens = vectorizer.get_feature_names_out()
# #Menjadikan hasil tfidf sebuah dataframe
df_tfidfvect = pd.DataFrame(data=tfidf_dataset.toarray(), index=dataset.index.values, columns = tfidf_tokens)

In [46]:
a= pd.DataFrame(data=df_tfidfvect)

In [47]:
a.to_excel("C:/Users/HP/Downloads/TUGAS AKHIR/NEW/" + "KamusKataTFIDFSkelarn.xlsx", index=False)

In [48]:
display(a)

,acacia,acer,acetate,acetyl,acetylated,achillea,acid,acids,acne,acneact,...,witch,wowtery,xanthan,xylitol,xylitylglucoside,yellow,ysb,zea,zeylanicum,zinc
0,0.0,0.0,0.080476,0.115209,0.000000,0.0,0.232215,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.078927,0.0,0.108635,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.000000,0.097488,0.0,0.160005,0.0,0.000000,0.0,...,0.0,0.153291,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.000000,0.101018,0.0,0.207249,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.000000,0.095813,0.0,0.235883,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.103857,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,0.0,0.0,0.113273,0.000000,0.132763,0.0,0.163426,0.0,0.000000,0.0,...,0.0,0.000000,0.088592,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.0,0.000000,0.109768,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.053682,0.0,0.000000,0.0,...,0.0,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# 5 RECOMMENDATION

## IMPORT DATA PENGGUNA

In [49]:
data_path = "C:\\Users\\HP\\Downloads\\DataPengguna4.csv"
data_pengguna = pd.read_csv(data_path)
data_pengguna.head(5)

,No,Jenis Produk,Jenis Kulit,Permasalahan Kulit,Kandungan
0,1,Facial Wash,Normal,Normal,NaN
1,2,Facial Wash,Normal,Kusam,"Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter"
2,3,Facial Wash,Normal,Jerawat,"Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil"
3,4,Facial Wash,Berminyak,Normal,"Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid"
4,5,Facial Wash,Berminyak,Kusam,"Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter"

In [50]:
data_pengguna = data_pengguna.drop(labels=["No"], axis='columns')

In [51]:
data_pengguna["Kandungan"].fillna(" ", inplace=True)

## MEMBUAT DATA KEMUNGKINAN INPUTAN PENGGUNA

In [52]:
data_pengguna['input'] = data_pengguna['Jenis Produk'] + " " +  data_pengguna['Jenis Kulit'] + " " + data_pengguna['Permasalahan Kulit'] + " " + data_pengguna['Kandungan']

data_pengguna.head(5)

,Jenis Produk,Jenis Kulit,Permasalahan Kulit,Kandungan,input
0,Facial Wash,Normal,Normal,,Facial Wash Normal Normal
1,Facial Wash,Normal,Kusam,"Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter","Facial Wash Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter"
2,Facial Wash,Normal,Jerawat,"Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil","Facial Wash Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil"
3,Facial Wash,Berminyak,Normal,"Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid","Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid"
4,Facial Wash,Berminyak,Kusam,"Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter","Facial Wash Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter"

In [53]:
data_pengguna['input'][0]

'Facial Wash Normal Normal  '

## 5 REKOMENDASI BERDASARKAN DATA INPUTAN PENGGUNA

In [54]:
for i in range (0,10):
  print(data_pengguna['input'][i]) 

  user_input = text_pre_input(data_pengguna['input'][i])
  print(user_input)
  index, top5 = get_recommendations_product(user_input, tfidf_dataset)

  res_data = pd.DataFrame(data_product[['Nama', 'Jenis ']].iloc[index])
  fix_res = res_data.join(top5)
  # display(res_data)
  # display(top5)
  display(fix_res)

Facial Wash Normal Normal
['facial', 'wash', 'normal', 'normal']

,Nama,Jenis,cosine similarity score
10,Kind Facial Wash 120ml,Facial Wash,0.249278
11,Facial Wash Gel (Sabun Wajah) Rose,Facial Wash,0.157216
17,Hydralife Mild Cleanser Foam,Facial Wash,0.123551
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.121655
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.114084

Facial Wash Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
['facial', 'wash', 'normal', 'kusam', 'hyaluronic', 'acid', 'alpha', 'hydroxy', 'acids', 'vitamin', 'niacinamide', 'shea', 'butter']

,Nama,Jenis,cosine similarity score
10,Kind Facial Wash 120ml,Facial Wash,0.065744
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.061209
23,Multi Acids Glowing Toner,Face Toner,0.059787
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.057218
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.054869

Facial Wash Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
['facial', 'wash', 'normal', 'jerawat', 'salicylic', 'acid', 'sulfur', 'azelaic', 'acid', 'alpha', 'hydroxy', 'acid', 'beta', 'hydroxy', 'acid', 'bha', 'tea', 'tree', 'oil']

,Nama,Jenis,cosine similarity score
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.092379
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.086723
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.086247
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.084944
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.080929

Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
['facial', 'wash', 'minyak', 'normal', 'dimethicone', 'glycolic', 'acid', 'hyaluronic', 'acid', 'niacinamide', 'retinol', 'salicylic', 'acid']

,Nama,Jenis,cosine similarity score
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.114287
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.102236
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.099161
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.095742
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.089539

Facial Wash Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter
['facial', 'wash', 'minyak', 'kusam', 'dimethicone', 'glycolic', 'acid', 'hyaluronic', 'acid', 'niacinamide', 'retinol', 'salicylic', 'acid', 'alpha', 'hydroxy', 'acids', 'vitamin', 'shea', 'butter']

,Nama,Jenis,cosine similarity score
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.072906
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.072632
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.064936
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.064903
23,Multi Acids Glowing Toner,Face Toner,0.063545

Facial Wash Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
['facial', 'wash', 'minyak', 'jerawat', 'dimethicone', 'glycolic', 'acid', 'hyaluronic', 'acid', 'niacinamide', 'retinol', 'salicylic', 'acid', 'sulfur', 'azelaic', 'acid', 'alpha', 'hydroxy', 'acid', 'beta', 'hydroxy', 'acid', 'bha', 'tea', 'tree', 'oil']

,Nama,Jenis,cosine similarity score
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.094153
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.085971
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.085610
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.075861
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.072153

Facial Wash Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
['facial', 'wash', 'kering', 'normal', 'hyaluronic', 'acid', 'glycerin', 'glycolic', 'acid', 'aloe', 'vera', 'lactic', 'acid', 'green', 'tea']

,Nama,Jenis,cosine similarity score
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.106829
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.091945
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.087175
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.086222
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.080406

Facial Wash Kering Kusam Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
['facial', 'wash', 'kering', 'kusam', 'hyaluronic', 'acid', 'glycerin', 'glycolic', 'acid', 'aloe', 'vera', 'lactic', 'acid', 'green', 'tea', 'alpha', 'hydroxy', 'acids', 'vitamin', 'niacinamide', 'shea', 'butter']

,Nama,Jenis,cosine similarity score
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.068268
23,Multi Acids Glowing Toner,Face Toner,0.065026
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.062133
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.061752
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.058266

Facial Wash Kering Jerawat Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
['facial', 'wash', 'kering', 'jerawat', 'hyaluronic', 'acid', 'glycerin', 'glycolic', 'acid', 'aloe', 'vera', 'lactic', 'acid', 'green', 'tea', 'salicylic', 'acid', 'sulfur', 'azelaic', 'acid', 'alpha', 'hydroxy', 'acid', 'beta', 'hydroxy', 'acid', 'bha', 'tea', 'tree', 'oil']

,Nama,Jenis,cosine similarity score
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.101336
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.086407
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.084537
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.078276
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.076049

Facial Wash Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E
['facial', 'wash', 'kombinasi', 'normal', 'hyaluronic', 'acid', 'lactic', 'acid', 'retinol', 'vitamin', 'vitamin']

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.101706
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.087222
99,Perfect Shield Sunscreen Normal To Dry Skin Spf 30/Pa++,Sunscreen,0.082153
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.082013
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.081580

# KODE 2

In [55]:
#TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import Normalizer

test_case = "Facial Wash Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E "

# TFIDF
vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))

the_data = data_product

if (test_case.find('Facial Wash')!=-1):
  print ('Facial Wash')
  tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][0:20])
  the_product = the_data[0:20]
elif (test_case.find('Face Toner')!=-1):
  print ('Face Toner')
  tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][20:40])
  the_product = the_data[20:40]
elif (test_case.find('Face Serum')!=-1):
  print('Face Serum')
  tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][40:60])
  the_product = the_data[40:60]
elif (test_case.find('Moisturizer')!=-1):
  print('Moisturizer')
  tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][60:80])
  the_product = the_data[60:80]
else :
  print('Sunscreen')
  tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][80:100])
  the_product = the_data[80:100]
  

user_input = text_pre_input(test_case)
index, top5 = get_recommendations_product(user_input, tfidf_dataset1)

res_data = pd.DataFrame(the_product[['Nama', 'Jenis ']].iloc[index])
top5.index = res_data.index
fix_res = pd.concat([res_data, top5], axis=1)
# display(res_data)

# display(top5)

# aha = top5.rename(index=res_data.index)
# display(aha)
display(fix_res)

# the_data

Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.107609
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.078824
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.076056
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.074174
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.074002

In [56]:
for i in range (0,10):
  print(data_pengguna['input'][i]) 

  test_case = data_pengguna['input'][i]

  # TFIDF
  vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))

  the_data = data_product

  if (test_case.find('Facial Wash')!=-1):
    print ('Facial Wash')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][0:20])
    the_product = the_data[0:20]
  elif (test_case.find('Face Toner')!=-1):
    print ('Face Toner')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][20:40])
    the_product = the_data[20:40]
  elif (test_case.find('Face Serum')!=-1):
    print('Face Serum')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][40:60])
    the_product = the_data[40:60]
  elif (test_case.find('Moisturizer')!=-1):
    print('Moisturizer')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][60:80])
    the_product = the_data[60:80]
  else :
    print('Sunscreen')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][80:100])
    the_product = the_data[80:100]
    

  user_input = text_pre_input(test_case)
  index, top5 = get_recommendations_product(user_input, tfidf_dataset1)

  res_data = pd.DataFrame(the_product[['Nama', 'Jenis ']].iloc[index])
  top5.index = res_data.index
  fix_res = pd.concat([res_data, top5], axis=1)
  display(fix_res)

Facial Wash Normal Normal
Facial Wash

,Nama,Jenis,cosine similarity score
10,Kind Facial Wash 120ml,Facial Wash,0.207778
11,Facial Wash Gel (Sabun Wajah) Rose,Facial Wash,0.124641
17,Hydralife Mild Cleanser Foam,Facial Wash,0.114029
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.092602
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.089304

Facial Wash Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.052116
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.051613
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.047605
10,Kind Facial Wash 120ml,Facial Wash,0.047568
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.046258

Facial Wash Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.095243
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.088247
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.084491
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.072936
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.069333

Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.103751
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.099441
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.087304
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.086267
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.081391

Facial Wash Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.073774
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.066144
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.058148
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.057394
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.053724

Facial Wash Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.092234
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.091824
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.075651
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.073640
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.069876

Facial Wash Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.098672
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.090469
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.089303
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.076591
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.075593

Facial Wash Kering Kusam Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.065580
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.064089
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.059253
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.055262
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.053293

Facial Wash Kering Jerawat Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.093196
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.093065
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.083182
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.082788
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.069449

Facial Wash Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.107609
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.078824
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.076056
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.074174
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.074002

In [57]:
for i in range (0,20):
  print(data_pengguna['input'][i]) 

  test_case = data_pengguna['input'][i]

  # TFIDF
  vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))

  the_data = data_product

  if (test_case.find('Facial Wash')!=-1):
    print ('Facial Wash')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][0:20])
    the_product = the_data[0:20]
  elif (test_case.find('Face Toner')!=-1):
    print ('Face Toner')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][20:40])
    the_product = the_data[20:40]
  elif (test_case.find('Face Serum')!=-1):
    print('Face Serum')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][40:60])
    the_product = the_data[40:60]
  elif (test_case.find('Moisturizer')!=-1):
    print('Moisturizer')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][60:80])
    the_product = the_data[60:80]
  else :
    print('Sunscreen')
    tfidf_dataset1 = vectorizer.fit_transform(dataset['data'][80:100])
    the_product = the_data[80:100]
    

  user_input = text_pre_input(test_case)
  index, top5 = get_recommendations_product(user_input, tfidf_dataset1)

  res_data = pd.DataFrame(the_product[['Nama', 'Jenis ']].iloc[index])
  top5.index = res_data.index
  fix_res = pd.concat([res_data, top5], axis=1)
  display(fix_res)

Facial Wash Normal Normal
Facial Wash

,Nama,Jenis,cosine similarity score
10,Kind Facial Wash 120ml,Facial Wash,0.207778
11,Facial Wash Gel (Sabun Wajah) Rose,Facial Wash,0.124641
17,Hydralife Mild Cleanser Foam,Facial Wash,0.114029
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.092602
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.089304

Facial Wash Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.052116
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.051613
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.047605
10,Kind Facial Wash 120ml,Facial Wash,0.047568
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.046258

Facial Wash Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.095243
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.088247
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.084491
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.072936
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.069333

Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.103751
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.099441
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.087304
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.086267
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.081391

Facial Wash Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.073774
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.066144
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.058148
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.057394
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.053724

Facial Wash Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.092234
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.091824
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.075651
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.073640
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.069876

Facial Wash Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.098672
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.090469
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.089303
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.076591
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.075593

Facial Wash Kering Kusam Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.065580
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.064089
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.059253
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.055262
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.053293

Facial Wash Kering Jerawat Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.093196
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.093065
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.083182
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.082788
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.069449

Facial Wash Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.107609
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.078824
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.076056
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.074174
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.074002

Facial Wash Kombinasi Kusam Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Alpha Hydroxy Acids (AHA), Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,cosine similarity score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.067434
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.052327
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.052041
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.050736
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.048887

Facial Wash Kombinasi Jerawat Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,cosine similarity score
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.089210
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.087519
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.084580
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.083222
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.070218

Face Toner Normal Normal
Face Toner

,Nama,Jenis,cosine similarity score
23,Multi Acids Glowing Toner,Face Toner,0.145637
36,Botanical Witch Hazel Toner,Face Toner,0.138881
27,Beneath Cloud Nine Essence Toner,Face Toner,0.125575
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.125142
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.122567

Face Toner Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Face Toner

,Nama,Jenis,cosine similarity score
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.087213
23,Multi Acids Glowing Toner,Face Toner,0.085281
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.078624
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.058902
32,Skin Ready Hydrating Booster,Face Toner,0.045837

Face Toner Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Toner

,Nama,Jenis,cosine similarity score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.107036
23,Multi Acids Glowing Toner,Face Toner,0.085568
22,Mild Purifying Toner,Face Toner,0.071136
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.060957
39,Cica Series Face Toner 30ml,Face Toner,0.060538

Face Toner Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Face Toner

,Nama,Jenis,cosine similarity score
23,Multi Acids Glowing Toner,Face Toner,0.108199
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.105393
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.089198
22,Mild Purifying Toner,Face Toner,0.082088
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.079096

Face Toner Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter
Face Toner

,Nama,Jenis,cosine similarity score
23,Multi Acids Glowing Toner,Face Toner,0.085804
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.070307
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.064584
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.059046
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.059040

Face Toner Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Toner

,Nama,Jenis,cosine similarity score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.088795
23,Multi Acids Glowing Toner,Face Toner,0.082592
22,Mild Purifying Toner,Face Toner,0.068195
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.068090
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.058748

Face Toner Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
Face Toner

,Nama,Jenis,cosine similarity score
23,Multi Acids Glowing Toner,Face Toner,0.113656
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.084729
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.081402
22,Mild Purifying Toner,Face Toner,0.077806
26,Beneath Dear Doris Essence Toner,Face Toner,0.063364

Face Toner Kering Kusam Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Face Toner

,Nama,Jenis,cosine similarity score
23,Multi Acids Glowing Toner,Face Toner,0.087661
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.065075
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.060827
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.054646
22,Mild Purifying Toner,Face Toner,0.049095

# JIKA INPUTAN PENGGUNA MASUK KE DALAM DATABASE

In [58]:
#TEXT PREPROCESSING INPUTAN
def text_pre_input_two (user_input):
  # CASE FOLDING
    user_input = user_input.lower()

  # TOKENIZING
    # Menghapus Angka
    user_input = re.sub(r"\d+", "", user_input)
    # Menghapus Tanda Baca
    user_input = user_input.translate(
        str.maketrans("", "", string.punctuation))
    # Menghapus Simbol (@)
    user_input = re.sub(r"@\S+", "", user_input)
    # Menghapus URL
    user_input = re.sub("http[s]?\://\S+", "", user_input)
    # Menghapus tab atau line karakter
    user_input = re.sub(r"\n", "", user_input)
    # Menghapus berlebihan spasi
    user_input = re.sub('\s+', ' ', user_input)
    # dilakukan proses tokenization pada user_input
    tokens_query = [str(tok) for tok in nltk.word_tokenize(user_input)]

  # FILTERING
    # Stopword Bahasa Indonesia
    indo_stopword = set(stopwords.words('indonesian'))

    # Stopword Bahasa Inggris
    eng_stopword = set(stopwords.words('english'))

    # Data Stopword
    data_stopword = str(indo_stopword) + " " + str(eng_stopword)

    # Data tanpa stopword
    tokens_query = [word for word in tokens_query if not word in data_stopword]

  # STEMMING
    the_query = []
    # Membuat stemmer
    Factory = StemmerFactory()
    Stemmer = Factory.create_stemmer()
    for i in range(0, len(tokens_query)):
        tokens_query[i] = Stemmer.stem(tokens_query[i])
        the_query.append(tokens_query[i])

    join_query = ' '.join(tokens_query)
    return (join_query)

In [59]:
#COSINE SIMILARITY AND GET THE RECOMMENDATION
from sklearn.metrics.pairwise import cosine_similarity

def get_recommendations_product_two(tfidf_dataset):

    # Mencari tingkat kemiripan antara user_input dengan dataset
    cos_sim = cosine_similarity(tfidf_dataset, tfidf_dataset)
    # print(cos_sim)
    df_cosim = pd.DataFrame(data=cos_sim)
    # display(df_cosim)

    #Mengambil nilai cosine similarity pada baris yang berisi inputan pengguna
    val_cos_sim = pd.DataFrame(data=cos_sim[-1,:], columns=['Cosine Similarity Score'])
    # display(val_cos_sim)

    # Mencari 5 teratas nilai kemiripan tertinggi
    top5 = val_cos_sim.sort_values("Cosine Similarity Score", ascending=False)[1:6]
    # display(top5)

    # Mencari index dari 5 nilai kemiripan teratas
    index = list(top5.index.values)

    return index, top5

In [60]:
pip install xlsxwriter

Requirement already satisfied: xlsxwriter in c:\users\hp\appdata\local\programs\python\python38\lib\site-packages (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [92]:
#TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer

# import xlsxwriter module
import xlsxwriter

#contoh inputan pengguna
test_case = "Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid"

# TFIDF vectorizer
vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))
# melakuka text preprocessing pada inputan pengguna
user_input = text_pre_input_two(test_case)
# menambahkan ke dalam dataset
add_data = pd.DataFrame({'data':user_input}, index=[-1])
# print(add_data)

# membuat variabel baru untuk menampung data product
the_data = data_product

#percabangan agar produk yang direkomendasikan sesuai dengan kategori
if (test_case.find('Facial Wash')!=-1):
  print ('Facial Wash')
  th_idx = pd.concat([dataset[0:20],add_data]).reset_index(drop=True)
  the_product = the_data[0:20]
elif (test_case.find('Face Toner')!=-1):
  print ('Face Toner')
  th_idx = pd.concat([dataset[20:40],add_data]).reset_index(drop=True)
  the_product = the_data[20:40]
elif (test_case.find('Face Serum')!=-1):
  print('Face Serum')
  th_idx = pd.concat([dataset[40:60],add_data]).reset_index(drop=True)
  the_product = the_data[40:60]
elif (test_case.find('Moisturizer')!=-1):
  print('Moisturizer')
  th_idx = pd.concat([dataset[60:80],add_data]).reset_index(drop=True)
  the_product = the_data[60:80]
else :
  print('Sunscreen')
  th_idx = pd.concat([dataset[80:100],add_data]).reset_index(drop=True)
  the_product = the_data[80:100]
  

tfidf_dataset1 = vectorizer.fit_transform(th_idx['data'])
index, top5 = get_recommendations_product_two(tfidf_dataset1)

res_data = pd.DataFrame(the_product[['Nama', 'Jenis ']].iloc[index])
top5.index = res_data.index
fix_res = pd.concat([res_data, top5], axis=1)

display(fix_res)

# Menuliskan hasil ke excel
writer = pd.ExcelWriter('C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/HasilRekomendasi2.xlsx', engine='xlsxwriter')
row = 2
col = 0
fix_res.to_excel(writer, startrow=row)

work_book = writer.book
work_sheet =  writer.sheets["Sheet1"]
row-=2
work_sheet.write(row, col, test_case)
row+= 3

writer.close()

Facial Wash

,Nama,Jenis,Cosine Similarity Score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.229273
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.203563
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.179483
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.172825
17,Hydralife Mild Cleanser Foam,Facial Wash,0.161652

## Jika dilakukan pada seluruh data pengguna

In [100]:
#TFIDF
from sklearn.feature_extraction.text import TfidfVectorizer

# import xlsxwriter module
import xlsxwriter

writer = pd.ExcelWriter('C:/Users/HP/Downloads/TUGAS AKHIR/EXCEL KODINGAN/HasilRekomendasi3.xlsx', engine='xlsxwriter')
row = 1
col = 0

for i in range (0,len(data_pengguna)):
  print(data_pengguna['input'][i])

  #contoh inputan pengguna
  test_case = data_pengguna['input'][i]

  # TFIDF vectorizer
  vectorizer = TfidfVectorizer(analyzer='word', stop_words=list(data_stopword))
  # melakuka text preprocessing pada inputan pengguna
  user_input = text_pre_input_two(test_case)
  # menambahkan ke dalam dataset
  add_data = pd.DataFrame({'data':user_input}, index=[-1])
  # print(add_data)

  # membuat variabel baru untuk menampung data product
  the_data = data_product

  #percabangan agar produk yang direkomendasikan sesuai dengan kategori
  if (test_case.find('Facial Wash')!=-1):
    print ('Facial Wash')
    th_idx = pd.concat([dataset[0:20],add_data]).reset_index(drop=True)
    the_product = the_data[0:20]
  elif (test_case.find('Face Toner')!=-1):
    print ('Face Toner')
    th_idx = pd.concat([dataset[20:40],add_data]).reset_index(drop=True)
    the_product = the_data[20:40]
  elif (test_case.find('Face Serum')!=-1):
    print('Face Serum')
    th_idx = pd.concat([dataset[40:60],add_data]).reset_index(drop=True)
    the_product = the_data[40:60]
  elif (test_case.find('Moisturizer')!=-1):
    print('Moisturizer')
    th_idx = pd.concat([dataset[60:80],add_data]).reset_index(drop=True)
    the_product = the_data[60:80]
  else :
    print('Sunscreen')
    th_idx = pd.concat([dataset[80:100],add_data]).reset_index(drop=True)
    the_product = the_data[80:100]
    
  tfidf_dataset1 = vectorizer.fit_transform(th_idx['data'])
  index, top5 = get_recommendations_product_two(tfidf_dataset1)

  res_data = pd.DataFrame(the_product[['Nama', 'Jenis ']].iloc[index])
  top5.index = res_data.index
  fix_res = pd.concat([res_data, top5], axis=1)
  display(fix_res)

  fix_res.to_excel(writer, startrow=row)
  work_book = writer.book
  work_sheet =  writer.sheets["Sheet1"]
  row-=1
  work_sheet.write(row, col, test_case)
  row+= 10

writer.close()

Facial Wash Normal Normal
Facial Wash

,Nama,Jenis,Cosine Similarity Score
10,Kind Facial Wash 120ml,Facial Wash,0.330705
11,Facial Wash Gel (Sabun Wajah) Rose,Facial Wash,0.198424
17,Hydralife Mild Cleanser Foam,Facial Wash,0.182355
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.147144
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.140751

Facial Wash Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,Cosine Similarity Score
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.101964
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.089200
8,Simply Bright Facial Wash Grape & Hyaluronic Acid,Facial Wash,0.087926
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.086791
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.081353

Facial Wash Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,Cosine Similarity Score
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.204726
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.197418
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.156980
1,Acne Facial Wash,Facial Wash,0.127196
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.125653

Facial Wash Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Facial Wash

,Nama,Jenis,Cosine Similarity Score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.229273
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.203563
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.179483
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.172825
17,Hydralife Mild Cleanser Foam,Facial Wash,0.161652

Facial Wash Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter
Facial Wash

,Nama,Jenis,Cosine Similarity Score
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.166673
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.140610
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.124029
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.119396
17,Hydralife Mild Cleanser Foam,Facial Wash,0.109538

Facial Wash Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,Cosine Similarity Score
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.215259
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.206763
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.194060
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.161676
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.145458

Facial Wash Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
Facial Wash

,Nama,Jenis,Cosine Similarity Score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.256506
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.211687
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.201826
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.187379
17,Hydralife Mild Cleanser Foam,Facial Wash,0.178486

Facial Wash Kering Kusam Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,Cosine Similarity Score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.177010
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.153492
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.150619
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.138909
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.128862

Facial Wash Kering Jerawat Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,Cosine Similarity Score
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.233475
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.233329
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.219823
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.206160
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.148642

Facial Wash Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E
Facial Wash

,Nama,Jenis,Cosine Similarity Score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.224024
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.152652
7,Simply Fresh Facial Wash Honey & Lemon,Facial Wash,0.131317
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.125523
8,Simply Bright Facial Wash Grape & Hyaluronic Acid,Facial Wash,0.124000

Facial Wash Kombinasi Kusam Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Alpha Hydroxy Acids (AHA), Niacinamide, Shea Butter
Facial Wash

,Nama,Jenis,Cosine Similarity Score
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.156906
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.105185
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.099954
0,Marigold Deep-Cleanse Facial Wash,Facial Wash,0.096805
7,Simply Fresh Facial Wash Honey & Lemon,Facial Wash,0.095187

Facial Wash Kombinasi Jerawat Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Facial Wash

,Nama,Jenis,Cosine Similarity Score
15,Tea Tree & Lemon Facial Cleanser,Facial Wash,0.224860
3,Hy! Amino Ac-TtackAnti-Acne Facial Wash,Facial Wash,0.202088
6,Golden Age Deep Cleansing Facial Wash,Facial Wash,0.196406
4,Hy! Amino Control Oil Control Facial Wash,Facial Wash,0.180587
5,Hy! Amino Glo-Win Brightening Facial Wash,Facial Wash,0.143858

Face Toner Normal Normal
Face Toner

,Nama,Jenis,Cosine Similarity Score
23,Multi Acids Glowing Toner,Face Toner,0.233246
36,Botanical Witch Hazel Toner,Face Toner,0.222827
27,Beneath Cloud Nine Essence Toner,Face Toner,0.201430
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.200381
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.196263

Face Toner Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Face Toner

,Nama,Jenis,Cosine Similarity Score
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.213339
23,Multi Acids Glowing Toner,Face Toner,0.188697
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.186093
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.123768
32,Skin Ready Hydrating Booster,Face Toner,0.100009

Face Toner Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.287979
23,Multi Acids Glowing Toner,Face Toner,0.147467
22,Mild Purifying Toner,Face Toner,0.129317
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.124785
39,Cica Series Face Toner 30ml,Face Toner,0.124083

Face Toner Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.269203
23,Multi Acids Glowing Toner,Face Toner,0.200336
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.196852
26,Beneath Dear Doris Essence Toner,Face Toner,0.177731
25,Miraculous Retinol Toner,Face Toner,0.168041

Face Toner Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter
Face Toner

,Nama,Jenis,Cosine Similarity Score
23,Multi Acids Glowing Toner,Face Toner,0.206585
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.190796
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.175778
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.159247
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.136727

Face Toner Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.264554
23,Multi Acids Glowing Toner,Face Toner,0.165921
25,Miraculous Retinol Toner,Face Toner,0.163545
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.157345
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.157059

Face Toner Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
Face Toner

,Nama,Jenis,Cosine Similarity Score
23,Multi Acids Glowing Toner,Face Toner,0.247023
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.207863
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.182970
26,Beneath Dear Doris Essence Toner,Face Toner,0.153182
22,Mild Purifying Toner,Face Toner,0.150155

Face Toner Kering Kusam Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Face Toner

,Nama,Jenis,Cosine Similarity Score
23,Multi Acids Glowing Toner,Face Toner,0.241916
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.189122
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.164722
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.157829
26,Beneath Dear Doris Essence Toner,Face Toner,0.121057

Face Toner Kering Jerawat Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.283952
23,Multi Acids Glowing Toner,Face Toner,0.204674
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.171046
22,Mild Purifying Toner,Face Toner,0.149682
25,Miraculous Retinol Toner,Face Toner,0.141281

Face Toner Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E
Face Toner

,Nama,Jenis,Cosine Similarity Score
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.228695
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.179578
23,Multi Acids Glowing Toner,Face Toner,0.149720
25,Miraculous Retinol Toner,Face Toner,0.145439
26,Beneath Dear Doris Essence Toner,Face Toner,0.133167

Face Toner Kombinasi Kusam Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Alpha Hydroxy Acids (AHA), Niacinamide, Shea Butter
Face Toner

,Nama,Jenis,Cosine Similarity Score
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.207374
23,Multi Acids Glowing Toner,Face Toner,0.175867
29,YOUR SKIN BAE SERIES Toner Niacinamide 7% + Alpha Arbutin 1% + Kale,Face Toner,0.171635
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.147187
26,Beneath Dear Doris Essence Toner,Face Toner,0.108731

Face Toner Kombinasi Jerawat Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Toner

,Nama,Jenis,Cosine Similarity Score
30,YOUR SKIN BAE SERIES Toner Salicylic Acid 1% + Zinc + Tea Tree Water,Face Toner,0.253969
24,Miraculous Divine Aura Essence-Toner X Paola Serena,Face Toner,0.161921
23,Multi Acids Glowing Toner,Face Toner,0.160031
25,Miraculous Retinol Toner,Face Toner,0.153070
28,YOUR SKIN BAE SERIES Toner - Essence Vitamin C 2% + Niacinamide 2% + Carrot Exctract Raspberry,Face Toner,0.137714

Face Serum Normal Normal
Face Serum

                                    Nama      Jenis   Cosine Similarity Score
59  Niacinamide - Brightening Serum 20ml  Face Serum                 0.283742
50                     Miracle Oil Serum  Face Serum                 0.266899
55              Niacinamide Skin Booster  Face Serum                 0.236128
51                Radiant Luminous Serum  Face Serum                 0.217909
52          Retinol Smooth Glowing Serum  Face Serum                 0.214168

Face Serum Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Face Serum

,Nama,Jenis,Cosine Similarity Score
59,Niacinamide - Brightening Serum 20ml,Face Serum,0.127032
55,Niacinamide Skin Booster,Face Serum,0.113074
54,Daily Defender Multivitamin Serum,Face Serum,0.096228
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.095140
58,Niacinamide 5% Beta Glucan 7 Phyto Extract Serum,Face Serum,0.088164

Face Serum Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Serum

,Nama,Jenis,Cosine Similarity Score
47,AHA-BHA-PHA Peeling Serum,Face Serum,0.249856
56,Centella Herb Serum,Face Serum,0.192194
57,AcnePlus Complete Solution Serum,Face Serum,0.138347
54,Daily Defender Multivitamin Serum,Face Serum,0.132754
58,Niacinamide 5% Beta Glucan 7 Phyto Extract Serum,Face Serum,0.126146

Face Serum Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.366764
52       Retinol Smooth Glowing Serum  Face Serum                 0.223044
54  Daily Defender Multivitamin Serum  Face Serum                 0.166607
57   AcnePlus Complete Solution Serum  Face Serum                 0.148849
42                    Acne Care Serum  Face Serum                 0.141366

Face Serum Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.248809
52       Retinol Smooth Glowing Serum  Face Serum                 0.157177
54  Daily Defender Multivitamin Serum  Face Serum                 0.117340
42                    Acne Care Serum  Face Serum                 0.097261
57   AcnePlus Complete Solution Serum  Face Serum                 0.097219

Face Serum Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.313962
56                Centella Herb Serum  Face Serum                 0.182046
57   AcnePlus Complete Solution Serum  Face Serum                 0.153865
54  Daily Defender Multivitamin Serum  Face Serum                 0.150196
42                    Acne Care Serum  Face Serum                 0.127744

Face Serum Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.378041
57   AcnePlus Complete Solution Serum  Face Serum                 0.191148
42                    Acne Care Serum  Face Serum                 0.171947
56                Centella Herb Serum  Face Serum                 0.169426
54  Daily Defender Multivitamin Serum  Face Serum                 0.145410

Face Serum Kering Kusam Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.267029
57   AcnePlus Complete Solution Serum  Face Serum                 0.142366
56                Centella Herb Serum  Face Serum                 0.131548
42                    Acne Care Serum  Face Serum                 0.130244
54  Daily Defender Multivitamin Serum  Face Serum                 0.120284

Face Serum Kering Jerawat Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.357079
56                Centella Herb Serum  Face Serum                 0.213410
57   AcnePlus Complete Solution Serum  Face Serum                 0.182371
42                    Acne Care Serum  Face Serum                 0.161051
54  Daily Defender Multivitamin Serum  Face Serum                 0.145754

Face Serum Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.214160
52       Retinol Smooth Glowing Serum  Face Serum                 0.204132
57   AcnePlus Complete Solution Serum  Face Serum                 0.125090
45     Tremella Daily Hydrating Serum  Face Serum                 0.110968
54  Daily Defender Multivitamin Serum  Face Serum                 0.104865

Face Serum Kombinasi Kusam Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Alpha Hydroxy Acids (AHA), Niacinamide, Shea Butter
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
52       Retinol Smooth Glowing Serum  Face Serum                 0.154969
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.152853
57   AcnePlus Complete Solution Serum  Face Serum                 0.097643
45     Tremella Daily Hydrating Serum  Face Serum                 0.097448
54  Daily Defender Multivitamin Serum  Face Serum                 0.094100

Face Serum Kombinasi Jerawat Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Face Serum

                                 Nama      Jenis   Cosine Similarity Score
47          AHA-BHA-PHA Peeling Serum  Face Serum                 0.286063
56                Centella Herb Serum  Face Serum                 0.163508
57   AcnePlus Complete Solution Serum  Face Serum                 0.156318
54  Daily Defender Multivitamin Serum  Face Serum                 0.131822
52       Retinol Smooth Glowing Serum  Face Serum                 0.118503

Moisturizer Normal Normal
Moisturizer

,Nama,Jenis,Cosine Similarity Score
70,Oil Free Brightening Daily Moisturizer,Moisturizer,0.177820
77,Aquabloom Moisturizer,Moisturizer,0.165868
76,PEPTINOL Granactive Retinoid + Peptide Night Moisturizer Crème,Moisturizer,0.161334
63,Daily Light Moisturizer,Moisturizer,0.142286
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.140978

Moisturizer Normal Kusam Hyaluronic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Moisturizer

,Nama,Jenis,Cosine Similarity Score
60,Licorice Creamy Light Moisturizer,Moisturizer,0.156642
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.116985
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.110535
67,Skin Oasis Barrier,Moisturizer,0.093409
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.090925

Moisturizer Normal Jerawat Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Moisturizer

,Nama,Jenis,Cosine Similarity Score
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.128386
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.125856
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.114603
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.105297
63,Daily Light Moisturizer,Moisturizer,0.084367

Moisturizer Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.281198
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.216618
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.171140
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.160717
68,Acneact Gentle Acne Moisturizer,Moisturizer,0.147142

Moisturizer Berminyak Kusam Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Alpha Hydroxy Acids (AHA), Vitamin C, Shea Butter
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.191223
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.154726
60,Licorice Creamy Light Moisturizer,Moisturizer,0.145860
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.123809
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.115672

Moisturizer Berminyak Jerawat Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.215503
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.181739
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.151685
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.125111
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.118992

Moisturizer Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.237261
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.195683
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.174432
65,Moringa Intense Soothing Moisturizing Gel,Moisturizer,0.155511
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.150264

Moisturizer Kering Kusam Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Alpha Hydroxy Acids (AHA), Vitamin C, Niacinamide, Shea Butter
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.166163
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.145264
60,Licorice Creamy Light Moisturizer,Moisturizer,0.140621
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.140548
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.111574

Moisturizer Kering Jerawat Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.203267
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.171282
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.167356
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.135134
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.122802

Moisturizer Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.186521
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.136912
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.124086
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.119979
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.106929

Moisturizer Kombinasi Kusam Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Alpha Hydroxy Acids (AHA), Niacinamide, Shea Butter
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.135861
60,Licorice Creamy Light Moisturizer,Moisturizer,0.129064
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.107673
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.097122
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.095897

Moisturizer Kombinasi Jerawat Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E, Salicylic Acid, Sulfur, Azelaic Acid, Alpha Hydroxy Acid (AHA), Beta Hydroxy Acid (BHA), Tea Tree Oil
Moisturizer

,Nama,Jenis,Cosine Similarity Score
72,Waterizer Light Weight Cream Hyaluronic Acid + Ceramide,Moisturizer,0.190108
79,Beneath Blueberry Cream Moisturizer,Moisturizer,0.147256
69,Marigold Memory Bounce Moisturizer,Moisturizer,0.146598
75,ACNEDOT Treatment Moisturizer Gel,Moisturizer,0.128752
78,Supple Power Hyaluronic9 + Onsen Moisture Bomb Gel,Moisturizer,0.117316

Sunscreen Normal Normal
Sunscreen

,Nama,Jenis,Cosine Similarity Score
86,Block It Out Sunscreen,Sunscreen,0.284884
99,Perfect Shield Sunscreen Normal To Dry Skin Spf 30/Pa++,Sunscreen,0.243192
96,Tone Up UV Elixir SPF 50+ PA++++,Sunscreen,0.238432
93,YSB Shield of Sun Essence SPF 50 PA++++,Sunscreen,0.233410
90,Skin Barrier Sunscreen SPF 50 PA++++,Sunscreen,0.170750

Sunscreen Berminyak Normal Dimethicone, Glycolic Acid, Hyaluronic Acid, Niacinamide, Retinol, Salicylic Acid
Sunscreen

                                     Nama     Jenis   Cosine Similarity Score
96       Tone Up UV Elixir SPF 50+ PA++++  Sunscreen                 0.203140
86                 Block It Out Sunscreen  Sunscreen                 0.196442
97             Hydramax-C Sunscreen Serum  Sunscreen                 0.190671
92                        Cloud Sunscreen  Sunscreen                 0.143249
87  Bodyguard Moisturiser Sunscreen Serum  Sunscreen                 0.133681

Sunscreen Kering Normal Hyaluronic Acid, Glycerin, Glycolic Acid, Aloe Vera, Lactic Acid, Green Tea
Sunscreen

,Nama,Jenis,Cosine Similarity Score
97,Hydramax-C Sunscreen Serum,Sunscreen,0.182792
96,Tone Up UV Elixir SPF 50+ PA++++,Sunscreen,0.182001
86,Block It Out Sunscreen,Sunscreen,0.176001
99,Perfect Shield Sunscreen Normal To Dry Skin Spf 30/Pa++,Sunscreen,0.170621
93,YSB Shield of Sun Essence SPF 50 PA++++,Sunscreen,0.108060

Sunscreen Kombinasi Normal Hyaluronic Acid, Lactic Acid, Retinol, Vitamin C, Vitamin E
Sunscreen

,Nama,Jenis,Cosine Similarity Score
99,Perfect Shield Sunscreen Normal To Dry Skin Spf 30/Pa++,Sunscreen,0.321559
86,Block It Out Sunscreen,Sunscreen,0.184387
96,Tone Up UV Elixir SPF 50+ PA++++,Sunscreen,0.172812
97,Hydramax-C Sunscreen Serum,Sunscreen,0.154495
93,YSB Shield of Sun Essence SPF 50 PA++++,Sunscreen,0.093855